/**
 * NODE-FLOW core suite: the port type table, the coercion table, connection
 * resolution and refusal, cycle handling, graph evaluation, and the derive-side
 * geometry (port anchors, wires) that the canvas and the painter share.
 *
 * WHAT THIS FILE IS FOR THAT THE DOCTESTS ARE NOT. Every pure function in
 * core/nodeflow.js carries executable examples and tests/doctest_test.js runs them,
 * so the per-function contracts are already pinned. This suite pins the things that
 * are true of the SYSTEM rather than of any one function:
 *   - the trio actually computes 3 × 2 = 6 THROUGH THE REGISTERED PLUGINS, not
 *     through a fixture that merely looks like them;
 *   - a connection is ordinary keyframable state, so the same graph on two slides
 *     produces two different pictures and a tween between them retweens the value;
 *   - the app.css --a-port-* mirror actually matches the core color table;
 *   - derive injects nodePorts and only for node widgets (every other document
 *     stays byte-identical);
 *   - refusals: type mismatch, missing port, and cycles, each with a sentence.
 */

import assert from "node:assert";
import * as T from "../core/transform.js";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  COERCIONS, NODE_INPUT_ROW_KIND, NODE_ITEM_REFS, PORT_BEAD_R, PORT_TYPES, PORT_TYPE_NAMES,
  coerce, coercionNote, compatibleSources, connectPairs, connectionRefusal, connectionsOf,
  declaredPorts, disconnectPairs, evaluateNodeGraph, findPort, isNodeWidget, nodeInputLabel,
  nodeInputRows,
  minimumNodeHeight, portAt, portColor, portLayout, portTypeCssVars, portZero,
  topoOrder, typesCompatible, wireBezierPath, wouldCycle,
} from "../core/nodeflow.js";
import { WIRE_HALO_INK, WIRE_WIDTH, wireOps } from "../core/node_chrome.js";
import { sceneIR } from "../render_gpu/ports.js";
import { parsePaint } from "../render_gpu/ir.js";
import { deriveRenderTree, deriveWires, nodePortAnchors, withDerivedInjections } from "../core/derive.js";
import { createRegistry } from "../core/registry.js";
import { registerPlugins } from "../plugins/index.js";
import { nodeMathPlugin } from "../plugins/node_math.js";
import { nodeNumberPlugin } from "../plugins/node_number.js";
import { displayReadout, nodeDisplayPlugin } from "../plugins/node_display.js";
import { foldState } from "../core/document.js";
import { evaluateState, slugMap } from "../core/expressions.js";

const HERE = dirname(fileURLToPath(import.meta.url));
let pass = 0;
const fails = [];
function check(name, fn) {
  try { fn(); pass++; } catch (e) { fails.push(`${name}: ${e.message}`); }
}

const registry = createRegistry();
registerPlugins(registry);

// ── THE TYPE TABLE ───────────────────────────────────────────────────────────

check("every port type declares a color, a label and a zero", () => {
  for (const name of PORT_TYPE_NAMES) {
    const t = PORT_TYPES[name];
    assert.match(t.color, /^#[0-9a-f]{6}$/i, `${name} color must be a hex literal (the painter cannot resolve a CSS var)`);
    assert.ok(t.label, `${name} needs a human label — refusal sentences read it`);
    assert.ok("zero" in t, `${name} needs a zero — an unconnected input must never read undefined`);
  }
});

check("portColor / portZero refuse an unknown type loudly", () => {
  assert.throws(() => portColor("nope"), /unknown port type/);
  assert.throws(() => portZero("nope"), /unknown port type/);
});

check("app.css mirrors the core port colors exactly", () => {
  // THE MIRROR IS NON-SILENT. The painter reads core literals; the DOM chrome reads
  // CSS tokens. Two lists of hexes drift the day someone tunes one — so the token
  // block is GENERATED by portTypeCssVars() and this asserts app.css contains it
  // verbatim. A tuned color in core with a stale token in CSS fails here.
  const css = readFileSync(join(HERE, "..", "web", "app.css"), "utf8");
  for (const line of portTypeCssVars().split("\n"))
    assert.ok(css.includes(line.trim()), `web/app.css is missing the generated token: ${line.trim()} — regenerate the --a-port-* block from core/nodeflow.portTypeCssVars()`);
});

// ── COERCION ─────────────────────────────────────────────────────────────────

check("every coercion entry names types that exist and carries a sentence", () => {
  for (const key of Object.keys(COERCIONS)) {
    const [from, to] = key.split("->");
    assert.ok(PORT_TYPES[from], `coercion ${key} names unknown source type ${from}`);
    assert.ok(PORT_TYPES[to], `coercion ${key} names unknown destination type ${to}`);
    assert.notStrictEqual(from, to, `${key} is an identity, which is not a coercion — remove it`);
    assert.ok(COERCIONS[key].why.length > 10, `${key} needs a sentence the user can read`);
    assert.strictEqual(typeof COERCIONS[key].convert, "function");
  }
});

check("identity is compatible and needs no coercion note", () => {
  for (const t of PORT_TYPE_NAMES) {
    assert.ok(typesCompatible(t, t));
    assert.strictEqual(coercionNote(t, t), null);
    assert.strictEqual(coerce(7, t, t), 7);
  }
});

check("an undeclared pair is incompatible, and coerce() throws rather than passing it through", () => {
  assert.ok(!typesCompatible("audio", "trigger"), "audio→trigger is not in the table");
  assert.throws(() => coerce(1, "audio", "trigger"), /no coercion/);
});

check("trigger→number is 0/1, not the raw value", () => {
  assert.strictEqual(coerce(true, "trigger", "number"), 1);
  assert.strictEqual(coerce(0, "trigger", "number"), 0);
});

// ── PORT DECLARATIONS ────────────────────────────────────────────────────────

check("a plugin with no ports() is not a node widget and answers the empty declaration", () => {
  const rect = registry.get("rect");
  assert.deepStrictEqual(declaredPorts(rect, rect.defaults), { inputs: [], outputs: [] });
  assert.strictEqual(isNodeWidget(rect), false);
});

check("the trio are node widgets and declare the ports the blueprint calls for", () => {
  assert.ok(isNodeWidget(nodeNumberPlugin));
  assert.ok(isNodeWidget(nodeMathPlugin));
  assert.ok(isNodeWidget(nodeDisplayPlugin));
  assert.deepStrictEqual(declaredPorts(nodeNumberPlugin, {}).outputs.map((p) => p.key), ["out"]);
  assert.deepStrictEqual(declaredPorts(nodeNumberPlugin, {}).inputs, []);
  assert.deepStrictEqual(declaredPorts(nodeMathPlugin, {}).inputs.map((p) => p.key), ["a", "b"]);
  assert.deepStrictEqual(declaredPorts(nodeDisplayPlugin, {}).inputs.map((p) => p.key), ["in"]);
  assert.deepStrictEqual(declaredPorts(nodeDisplayPlugin, {}).outputs, []);
});

check("a port declaring an unknown type is refused at declaration, not at connect", () => {
  assert.throws(() => declaredPorts({ type: "bad", ports: () => ({ inputs: [{ key: "x", type: "colour" }] }) }, {}), /unknown type/);
  assert.throws(() => declaredPorts({ type: "bad", ports: () => ({ inputs: [{ type: "number" }] }) }, {}), /has no key/);
});

check("ports are a FUNCTION OF STATE, so a port list can grow (the mixer case)", () => {
  const mixer = { type: "mix", ports: (s) => ({ inputs: Array.from({ length: s.channels ?? 2 }, (_, i) => ({ key: `in${i}`, type: "audio" })) }) };
  assert.strictEqual(declaredPorts(mixer, { channels: 2 }).inputs.length, 2);
  assert.strictEqual(declaredPorts(mixer, { channels: 8 }).inputs.length, 8);
});

check("every node plugin declares itemRefs so a duplicated patch remaps", () => {
  // WHY THIS MATTERS: without it, copy/pasting a whole patch leaves the copies
  // wired to the ORIGINALS — the copy looks right and is silently reading someone
  // else's values. plugins/group.js `members` is the same mechanism.
  for (const p of [nodeNumberPlugin, nodeMathPlugin, nodeDisplayPlugin])
    assert.deepStrictEqual(p.itemRefs, NODE_ITEM_REFS, `${p.type} must spread NODE_ITEM_REFS`);
});

// ── GEOMETRY ─────────────────────────────────────────────────────────────────

check("inputs sit on the LEFT edge and outputs on the RIGHT (the left-to-right ruling)", () => {
  const layout = portLayout(nodeMathPlugin, { w: 150, h: 90 });
  for (const p of layout)
    assert.strictEqual(p.x, p.side === "input" ? 0 : 150, `${p.key} is on the wrong edge`);
});

check("a node's default height fits its own port column", () => {
  for (const p of [nodeNumberPlugin, nodeMathPlugin, nodeDisplayPlugin])
    assert.ok(p.defaults.h >= minimumNodeHeight(p, p.defaults), `${p.type} is born too short for its beads`);
});

check("portAt: the bead wins inside its radius and nowhere else", () => {
  const s = { w: 150, h: 90 };
  assert.strictEqual(portAt(nodeMathPlugin, s, 0, 34, 0)?.key, "a", "dead on the first input bead");
  assert.strictEqual(portAt(nodeMathPlugin, s, PORT_BEAD_R - 0.5, 34, 0)?.key, "a", "just inside the radius");
  assert.strictEqual(portAt(nodeMathPlugin, s, PORT_BEAD_R + 2, 34, 0), null, "just outside: an ordinary body drag");
  assert.strictEqual(portAt(nodeMathPlugin, s, 75, 60, 0), null, "middle of the card: an ordinary body drag");
});

check("portAt tolerance widens the grab without moving the bead", () => {
  const s = { w: 150, h: 90 };
  assert.strictEqual(portAt(nodeMathPlugin, s, PORT_BEAD_R + 3, 34, 0), null);
  assert.strictEqual(portAt(nodeMathPlugin, s, PORT_BEAD_R + 3, 34, 6)?.key, "a");
});

check("nodePortAnchors wraps local→world, so a MOVED node's beads move with it", () => {
  const node = { itemId: "m", world: { x: 40, y: 12, rotation: 0, scale: 1 }, state: { w: 150, h: 90 }, plugin: nodeMathPlugin };
  const anchors = nodePortAnchors(node);
  assert.strictEqual(anchors.find((a) => a.key === "a").x, 40);
  assert.strictEqual(anchors.find((a) => a.key === "out").x, 190);
  assert.strictEqual(anchors.find((a) => a.key === "a").y, 46);
});

check("nodePortAnchors follows ROTATION and SCALE, so a rotated node's wires land on its beads", () => {
  // A QUARTER TURN about the item origin, at 2x. `world.rotation` is in RADIANS
  // (core/transform.js) — a fact worth pinning here, because the same anchors feed
  // the wire layer and the bead hit test, and a degrees/radians mix-up would put
  // every wire endpoint somewhere no bead can be grabbed.
  const world = { x: 0, y: 0, rotation: Math.PI / 2, scale: 2 };
  const node = { itemId: "m", world, state: { w: 100, h: 90 }, plugin: nodeMathPlugin };
  const out = nodePortAnchors(node).find((a) => a.key === "out");
  // local (100, 34) → scale 2 → (200, 68) → +90°: (x, y) ↦ (−y, x) → (−68, 200)
  assert.ok(Math.abs(out.x - -68) < 1e-9, `rotated output x: want -68, got ${out.x}`);
  assert.ok(Math.abs(out.y - 200) < 1e-9, `rotated output y: want 200, got ${out.y}`);
  // AND THE HIT TEST AGREES: inverting the same world puts the bead back at its
  // declared LOCAL position, which is the property that makes one geometry enough.
  const back = T.apply(T.invert(world), out.x, out.y);
  assert.ok(Math.abs(back.x - 100) < 1e-9 && Math.abs(back.y - 34) < 1e-9, "world→local round trip lands on the declared bead");
});

check("a non-node widget answers no port anchors, so every consumer may call unconditionally", () => {
  assert.deepStrictEqual(nodePortAnchors({ itemId: "r", world: { x: 0, y: 0, rotation: 0, scale: 1 }, state: { w: 10, h: 10 }, plugin: registry.get("rect") }), []);
});

// ── CONNECTIONS AND REFUSAL ──────────────────────────────────────────────────

const trio = (extra = {}) => ({
  src: { type: "node_number", x: 0, y: 0, w: 130, h: 90, value: 3 },
  mul: { type: "node_math", x: 300, y: 0, w: 150, h: 90, op: "multiply", inputs: { a: { item: "src", port: "out" }, b: { item: "two", port: "out" } } },
  two: { type: "node_number", x: 0, y: 200, w: 130, h: 90, value: 2 },
  disp: { type: "node_display", x: 600, y: 0, w: 140, h: 90, inputs: { in: { item: "mul", port: "out" } } },
  ...extra,
});

check("connectionsOf reads every wire, in deterministic order", () => {
  const c = connectionsOf(trio());
  assert.strictEqual(c.length, 3);
  assert.deepStrictEqual(c.map((e) => `${e.from.item}.${e.from.port}->${e.to.item}.${e.to.port}`).sort(),
    ["mul.out->disp.in", "src.out->mul.a", "two.out->mul.b"]);
});

check("a wire to an item that is not on this slide simply is not drawn — no error", () => {
  const items = trio();
  items.two.active = false;
  const c = connectionsOf(items);
  assert.strictEqual(c.length, 2, "the two→mul wire vanishes with its source");
  assert.ok(items.mul.inputs.b, "and the connection LEAF survives in the document, so the wire returns with the item");
});

check("connectionRefusal allows a legal number→number drop", () => {
  assert.strictEqual(connectionRefusal(trio(), registry, { item: "src", port: "out" }, { item: "mul", port: "a" }), null);
});

check("connectionRefusal names a missing port rather than failing obscurely", () => {
  assert.match(connectionRefusal(trio(), registry, { item: "src", port: "nope" }, { item: "mul", port: "a" }), /no output named "nope"/);
  assert.match(connectionRefusal(trio(), registry, { item: "src", port: "out" }, { item: "mul", port: "nope" }), /no input named "nope"/);
  assert.match(connectionRefusal(trio(), registry, { item: "ghost", port: "out" }, { item: "mul", port: "a" }), /source widget is not on this slide/);
});

check("an incompatible pair is refused with a sentence naming both TYPE LABELS", () => {
  const reg = { get: (t) => t === "a" ? { ports: () => ({ outputs: [{ key: "o", type: "audio" }] }) } : { ports: () => ({ inputs: [{ key: "i", type: "trigger" }] }) } };
  const why = connectionRefusal({ a: { type: "a" }, b: { type: "b" } }, reg, { item: "a", port: "o" }, { item: "b", port: "i" });
  assert.match(why, /Audio/);
  assert.match(why, /Trigger/);
  assert.match(why, /no conversion/);
});

check("a COERCIBLE pair is allowed and its note explains what the wire will do", () => {
  const reg = { get: (t) => t === "a" ? { ports: () => ({ outputs: [{ key: "o", type: "trigger" }] }) } : { ports: () => ({ inputs: [{ key: "i", type: "number" }] }) } };
  assert.strictEqual(connectionRefusal({ a: { type: "a" }, b: { type: "b" } }, reg, { item: "a", port: "o" }, { item: "b", port: "i" }), null);
  assert.match(coercionNote("trigger", "number"), /1 while high/);
});

// ── CYCLES ───────────────────────────────────────────────────────────────────

check("a cycle is REFUSED AT CONNECT TIME, with a sentence about the loop", () => {
  // disp is already downstream of src, so wiring disp back into src closes a loop.
  // disp has no outputs, so use mul→src, which is the same shape.
  const why = connectionRefusal(trio(), registry, { item: "mul", port: "out" }, { item: "src", port: "a" });
  // src has no inputs at all, so the port check fires first — that is the correct
  // precedence (a nonexistent port makes the cycle question meaningless). Prove
  // the cycle rule itself on a graph where both ports exist:
  assert.match(why, /no input named/);
  const items = trio({ mid: { type: "node_math", x: 0, y: 400, w: 150, h: 90, inputs: { a: { item: "mul", port: "out" } } } });
  assert.match(connectionRefusal(items, registry, { item: "mid", port: "out" }, { item: "mul", port: "a" }), /would make a loop/);
});

check("a self-connection is a cycle of length one and is caught by the same rule", () => {
  assert.ok(wouldCycle(trio(), registry, { item: "mul", port: "out" }, { item: "mul", port: "a" }));
});

check("a legal parallel path is NOT a cycle (a diamond is fine)", () => {
  const items = trio({ other: { type: "node_math", x: 0, y: 500, w: 150, h: 90, inputs: { a: { item: "src", port: "out" } } } });
  assert.ok(!wouldCycle(items, registry, { item: "other", port: "out" }, { item: "disp", port: "in" }),
    "src feeds both mul and other; joining them downstream is a diamond, not a loop");
});

check("a port declaring feedbackSafe is exempt from the cycle rule (the reserved audio escape)", () => {
  const reg = {
    get: () => ({ ports: () => ({ inputs: [{ key: "i", type: "audio" }, { key: "fb", type: "audio", feedbackSafe: true }], outputs: [{ key: "o", type: "audio" }] }) }),
  };
  const items = { a: { type: "n", inputs: { fb: { item: "b", port: "o" } } }, b: { type: "n" } };
  // b→a exists but enters a feedbackSafe port, so a→b does NOT close a loop.
  assert.ok(!wouldCycle(items, reg, { item: "a", port: "o" }, { item: "b", port: "i" }));
  // The same edge on an ORDINARY port does close one.
  const strict = { a: { type: "n", inputs: { i: { item: "b", port: "o" } } }, b: { type: "n" } };
  assert.ok(wouldCycle(strict, reg, { item: "a", port: "o" }, { item: "b", port: "i" }));
});

check("topoOrder survives a hand-edited cyclic document instead of hanging, and names the cycle", () => {
  const items = { a: { type: "x", inputs: { i: { item: "b", port: "o" } } }, b: { type: "x", inputs: { i: { item: "a", port: "o" } } } };
  const { order, cyclic } = topoOrder(items);
  assert.deepStrictEqual(order.slice().sort(), ["a", "b"], "every item still appears exactly once");
  assert.deepStrictEqual(cyclic.slice().sort(), ["a", "b"], "and the cycle is REPORTED, not swallowed");
});

// ── EVALUATION: THE PROOF ────────────────────────────────────────────────────

check("THE PROOF: 3 → ×2 → display shows 6, through the REGISTERED plugins", () => {
  const { values } = evaluateNodeGraph(trio(), registry);
  assert.strictEqual(values.src.outputs.out, 3);
  assert.strictEqual(values.two.outputs.out, 2);
  assert.strictEqual(values.mul.outputs.out, 6);
  assert.strictEqual(values.disp.inputs.in, 6);
  assert.strictEqual(displayReadout({ nodePorts: values.disp }), "6");
});

check("an unconnected input reads its type's ZERO, so a half-built patch still computes", () => {
  const items = { m: { type: "node_math", op: "add", inputs: { a: { item: "s", port: "out" } } }, s: { type: "node_number", value: 5 } };
  const { values } = evaluateNodeGraph(items, registry);
  assert.strictEqual(values.m.inputs.b, 0, "b is unwired");
  assert.strictEqual(values.m.outputs.out, 5, "5 + 0");
});

check("a SINK (no computeOutputs) receives inputs and produces nothing wireable", () => {
  const { values } = evaluateNodeGraph(trio(), registry);
  assert.deepStrictEqual(values.disp.outputs, {});
});

check("evaluation is order-independent: the topological pass, not the item map's key order", () => {
  const forward = evaluateNodeGraph(trio(), registry).values.disp.inputs.in;
  const items = trio();
  // Rebuild the SAME graph with the keys in the opposite order.
  const reversed = Object.fromEntries(Object.entries(items).reverse());
  assert.strictEqual(evaluateNodeGraph(reversed, registry).values.disp.inputs.in, forward);
});

check("a document with NO node widgets evaluates to nothing and costs nothing", () => {
  const { values, cyclic } = evaluateNodeGraph({ r: { type: "rect", x: 0, y: 0, w: 5, h: 5 } }, registry);
  assert.deepStrictEqual(values, {});
  assert.deepStrictEqual(cyclic, []);
});

check("division by zero reads as Infinity and the card names it, rather than throwing", () => {
  const items = { s: { type: "node_number", value: 1 }, z: { type: "node_number", value: 0 }, d: { type: "node_math", op: "divide", inputs: { a: { item: "s", port: "out" }, b: { item: "z", port: "out" } } } };
  assert.strictEqual(evaluateNodeGraph(items, registry).values.d.outputs.out, Infinity);
  assert.strictEqual(displayReadout({ nodePorts: { inputs: { in: Infinity } } }), "∞");
});

// ── DERIVE INTEGRATION ───────────────────────────────────────────────────────

check("derive injects nodePorts on node widgets ONLY (every other document stays identical)", () => {
  const nodes = deriveRenderTree({ items: { ...trio(), r: { type: "rect", x: 0, y: 0, w: 5, h: 5 } } }, registry);
  const disp = nodes.find((n) => n.itemId === "disp");
  assert.strictEqual(disp.state.nodePorts.inputs.in, 6, "the display's derived state carries what its wire brought");
  const r = nodes.find((n) => n.itemId === "r");
  assert.ok(!("nodePorts" in r.state), "a rect gains no key at all");
});

check("withDerivedInjections returns the VERY SAME OBJECT when nothing is injected", () => {
  const s = { w: 1 };
  assert.strictEqual(withDerivedInjections(s, { type: "rect" }, {}, undefined), s, "=== identity: this is what keeps existing documents byte-identical");
});

check("the display's PICTURE shows the computed number (emit, not just state)", () => {
  const nodes = deriveRenderTree({ items: trio() }, registry);
  const disp = nodes.find((n) => n.itemId === "disp");
  const ops = disp.plugin.emit(disp.state, null, disp.world);
  const texts = ops.filter((o) => o.op === "text").map((o) => o.text);
  assert.ok(texts.includes("6"), `the display list must literally contain "6"; got ${JSON.stringify(texts)}`);
});

check("deriveWires produces one wire per resolved connection, colored by the SOURCE port's type", () => {
  const wires = deriveWires(deriveRenderTree({ items: trio() }, registry));
  assert.strictEqual(wires.length, 3);
  for (const w of wires) {
    assert.strictEqual(w.type, "number");
    assert.ok(Number.isFinite(w.from.x) && Number.isFinite(w.to.x), "both endpoints are world points");
  }
  const last = wires.find((w) => w.to.item === "disp");
  assert.strictEqual(last.from.item, "mul");
});

check("a wire whose endpoint node is off this slide is simply not drawn", () => {
  const items = trio();
  items.mul.active = false;
  const wires = deriveWires(deriveRenderTree({ items }, registry));
  assert.strictEqual(wires.length, 0, "mul carried two of the three wires and terminated the third");
});

check("WIRES ARE NOT WIDGETS: no wire ever becomes a render node or an item", () => {
  const nodes = deriveRenderTree({ items: trio() }, registry);
  assert.strictEqual(nodes.length, 4, "four items in, four nodes out — wires add none");
  for (const n of nodes) assert.ok(registry.get(n.type), `${n.type} must be a registered widget type`);
});

// ── CONNECTIONS ARE ORDINARY KEYFRAMABLE STATE ───────────────────────────────

check("connect/disconnect produce [path, value] pairs for the ONE undo path", () => {
  assert.deepStrictEqual(connectPairs({ item: "a", port: "out" }, { item: "b", port: "x" }),
    [[["items", "b", "inputs", "x"], { item: "a", port: "out" }]]);
  // NULL, not a deleted key: state is FOLDED, so removing the key would let the
  // connection be inherited from an earlier slide and the wire would come back.
  assert.deepStrictEqual(disconnectPairs({ item: "b", port: "x" }), [[["items", "b", "inputs", "x"], null]]);
});

check("a null connection reads as disconnected, so the disconnect value needs no special reader", () => {
  const items = trio();
  items.disp.inputs.in = null;
  assert.strictEqual(connectionsOf(items).filter((e) => e.to.item === "disp").length, 0);
  assert.strictEqual(evaluateNodeGraph(items, registry).values.disp.inputs.in, 0);
});

check("A PATCH MAY DIFFER PER SLIDE: the same items, rewired on slide 2", () => {
  // The whole reason connections live in ordinary state. Slide 0 wires src(3)→disp;
  // slide 1 rewires disp to read `two`(2) instead. Nothing in nodeflow.js knows
  // about slides — this works because a connection is a state leaf like any other.
  const doc = {
    meta: { slideW: 1280, slideH: 720 },
    slides: [
      { id: "s0", name: "one", delta: { items: {
        cam: { type: "camera", x: 0, y: 0, w: 1280, h: 720 },
        src: { type: "node_number", x: 0, y: 0, w: 130, h: 90, value: 3 },
        two: { type: "node_number", x: 0, y: 200, w: 130, h: 90, value: 2 },
        disp: { type: "node_display", x: 400, y: 0, w: 140, h: 90, inputs: { in: { item: "src", port: "out" } } },
      } } },
      { id: "s1", name: "two", delta: { items: { disp: { inputs: { in: { item: "two", port: "out" } } } } } },
    ],
  };
  const at = (i) => evaluateNodeGraph(evaluateState(foldState(doc, i, 1), registry).state.items, registry).values.disp.inputs.in;
  assert.strictEqual(at(0), 3, "slide 0 reads the source of 3");
  assert.strictEqual(at(1), 2, "slide 1 was REWIRED to the source of 2");
});

check("A SOURCE'S VALUE RETWEENS ACROSS SLIDES like any other number", () => {
  // The other half of the same claim: the GRAPH is keyframable, and so is what
  // flows through it. A source keyframed 0→10 drives a doubler; at alpha 0.5 the
  // display must read 10, not 0 or 20.
  const doc = {
    meta: { slideW: 1280, slideH: 720 },
    slides: [
      { id: "s0", name: "one", delta: { items: {
        cam: { type: "camera", x: 0, y: 0, w: 1280, h: 720 },
        src: { type: "node_number", x: 0, y: 0, w: 130, h: 90, value: 0 },
        two: { type: "node_number", x: 0, y: 200, w: 130, h: 90, value: 2 },
        mul: { type: "node_math", x: 200, y: 0, w: 150, h: 90, op: "multiply", inputs: { a: { item: "src", port: "out" }, b: { item: "two", port: "out" } } },
        disp: { type: "node_display", x: 400, y: 0, w: 140, h: 90, inputs: { in: { item: "mul", port: "out" } } },
      } } },
      { id: "s1", name: "two", delta: { items: { src: { value: 10 } } } },
    ],
  };
  const at = (alpha) => evaluateNodeGraph(evaluateState(foldState(doc, 1, alpha), registry).state.items, registry).values.disp.inputs.in;
  assert.strictEqual(at(0), 0, "start of the transition: 0 × 2");
  assert.strictEqual(at(0.5), 10, "MID-TWEEN: 5 × 2 — the graph retweens because its inputs do");
  assert.strictEqual(at(1), 20, "end: 10 × 2");
});

check("an EQUATION drives a node source, so a patch can read the rest of the document", () => {
  const doc = {
    meta: { slideW: 1280, slideH: 720 },
    slides: [{ id: "s0", name: "one", delta: { items: {
      cam: { type: "camera", x: 0, y: 0, w: 1280, h: 720 },
      box: { type: "rect", name: "box", x: 0, y: 0, w: 42, h: 10 },
      src: { type: "node_number", x: 0, y: 0, w: 130, h: 90, value: "box.w" },
      disp: { type: "node_display", x: 400, y: 0, w: 140, h: 90, inputs: { in: { item: "src", port: "out" } } },
    } } }],
  };
  const state = evaluateState(foldState(doc, 0, 1), registry).state;
  assert.strictEqual(evaluateNodeGraph(state.items, registry).values.disp.inputs.in, 42,
    "`= box.w` reached the node graph with no node-specific equation code at all");
});

// ── THE AUDIO ROSTER, SWEPT THROUGH THE GENERAL NODE PROTOCOL (NF-BIND) ─────
// tests/audio_nodes_test.js checks the audio nodes against the ENGINE. These two
// check them against THIS file's contract instead — that 23 new node widgets did not
// quietly bend the general protocol to fit audio, which is the thing ADDENDUM 1
// forbids ("this whole workflow should be possible to change the feature without
// breaking the audio components and vice versa").

check("every AUDIO node satisfies the general node-widget protocol", () => {
  const audio = registry.all().filter((p) => p.audioModule);
  assert.ok(audio.length >= 23, `expected the full audio roster, found ${audio.length}`);
  for (const plugin of audio) {
    assert.ok(isNodeWidget(plugin, plugin.defaults), `${plugin.type} does not read as a node widget`);
    const ports = declaredPorts(plugin, plugin.defaults);
    assert.ok(Array.isArray(ports.inputs) && Array.isArray(ports.outputs), `${plugin.type}'s ports() is malformed`);
    for (const side of ["inputs", "outputs"])
      for (const port of ports[side]) {
        assert.ok(typeof port.key === "string" && port.key, `${plugin.type} has a ${side} port with no key`);
        assert.ok(PORT_TYPE_NAMES.includes(port.type), `${plugin.type}.${port.key} has undeclared type "${port.type}"`);
        assert.ok(typeof port.label === "string" && port.label, `${plugin.type}.${port.key} has no label`);
        // findPort is what the wire gesture resolves a drop through; a port the
        // protocol cannot find is a bead nothing can land on.
        assert.ok(findPort(plugin, plugin.defaults, side === "inputs" ? "input" : "output", port.key),
          `${plugin.type}.${port.key} is declared but findPort cannot resolve it`);
      }
    // Port keys must be unique per side, or a connection could not name one.
    for (const side of ["inputs", "outputs"]) {
      const keys = ports[side].map((q) => q.key);
      assert.strictEqual(new Set(keys).size, keys.length, `${plugin.type} has duplicate ${side} port keys`);
    }
  }
});

check("the coercion table covers every port-type pair the audio roster can actually produce", () => {
  // THE POINT: a wire the roster makes REACHABLE but the table refuses is a bead a
  // user can drag from to a bead that lights up as illegal, with no way to tell from
  // the picture that the pair was never intended. This does not demand that every
  // pair be legal — it reports which reachable pairs are refused, so the refusals are
  // a DECISION on record rather than an oversight.
  const audio = registry.all().filter((p) => p.audioModule);
  const outTypes = new Set(), inTypes = new Set();
  for (const plugin of audio) {
    const ports = declaredPorts(plugin, plugin.defaults);
    for (const q of ports.outputs) outTypes.add(q.type);
    for (const q of ports.inputs) inTypes.add(q.type);
  }
  const refused = [];
  for (const from of outTypes) for (const to of inTypes) if (!typesCompatible(from, to)) refused.push(`${from}->${to}`);
  // audio->trigger is the ONE refused reachable pair, and it is refused DELIBERATELY:
  // turning a continuous signal into discrete events is a real operation with a real
  // parameter (Schmitt hysteresis), and that operation is the Trigger MODULE. A
  // silent coercion would have made the module pointless and the timing wrong.
  //
  // THIS SWEEP ALREADY EARNED ITS KEEP: it also reported `trigger->audio`, which was
  // reachable (the Trigger module emits one, nine modules accept the other) and had
  // NO such justification — a gate simply IS a signal. That was a real gap, found by
  // enumeration rather than by reasoning, and the coercion is now in the table. The
  // assertion is what makes the NEXT gap show up as a decision to make.
  assert.deepStrictEqual(refused.sort(), ["audio->trigger"],
    "a reachable port-type pair is refused with no module to bridge it — either add the coercion or add the module");
});

// ── THE WIRES ARE SCENE CONTENT (WORKSTREAM BN) ──────────────────────────────
//
// User, 2026-08-03: "the wires between nodes should be shown in prsentation mode
// and pdf rener and png render etc too please". Before this, a wire was an SVG
// path in web/CanvasView.svelte alone, so every consumer that is not the editor
// canvas drew naked nodes. These pins are about the SEAM, not about any one
// backend: a wire that reaches the display list reaches all of them, because
// `path` + stroke is an op every backend has drawn since before nodes existed.

check("a connected trio puts WIRE OPS in the display list — the whole point of BN", () => {
  const ir = sceneIR(deriveRenderTree({ items: trio() }, registry));
  // Two ops per wire (halo + wire) and three wires in the trio.
  const wireish = ir.filter((o) => o.op === "path" && typeof o.d === "string" && o.d.startsWith("M "));
  assert.strictEqual(wireish.length, 6, `three wires × (halo + wire); got ${wireish.length} path ops`);
  // The CURVE is the same one the editor's ghost draws — one function, so the wire
  // that replaces a ghost cannot land on a different path.
  const wires = deriveWires(deriveRenderTree({ items: trio() }, registry));
  const expected = new Set(wires.map((w) => wireBezierPath(w.from, w.to)));
  for (const op of wireish) assert.ok(expected.has(op.d), `${op.d} is not one of the three derived wire curves`);
});

check("wires are emitted UNDER the nodes, so a card never has a cable struck across its readout", () => {
  const ir = sceneIR(deriveRenderTree({ items: trio() }, registry));
  const firstNodeOp = ir.findIndex((o) => o.op === "pushTransform");
  const lastWireOp = ir.map((o, i) => [o, i]).filter(([o]) => o.op === "path" && String(o.d).startsWith("M ")).pop()[1];
  assert.ok(lastWireOp < firstNodeOp,
    `every wire op must precede the first node's pushTransform (wire ${lastWireOp} vs node ${firstNodeOp})`);
});

check("a wire carries the SOURCE port type's colour — the SAME table the beads read", () => {
  const ir = sceneIR(deriveRenderTree({ items: trio() }, registry));
  // portColor returns the hex literal; ir.js parses paints to RGBA floats, so compare
  // through the same parse rather than against a hand-written tuple that could drift.
  const want = parsePaint(portColor("number"));
  const wireStrokes = ir
    .filter((o) => o.op === "path" && String(o.d).startsWith("M ") && o.strokeWidth === WIRE_WIDTH)
    .map((o) => o.stroke);
  assert.strictEqual(wireStrokes.length, 3, "three wires, three type-coloured strokes");
  for (const s of wireStrokes) assert.deepStrictEqual(s, want, "a wire must be its source type's colour");
});

check("the HALO is wider, dimmer, and drawn BEFORE its own wire", () => {
  const ops = wireOps({ from: { x: 0, y: 0 }, to: { x: 200, y: 0 }, type: "number" });
  const [halo, wire] = ops;
  assert.ok(halo.strokeWidth > wire.strokeWidth, "the halo must be the wider stroke or it does not separate anything");
  assert.ok(halo.opacity < 1 && wire.opacity === 1, "the halo is the dim one");
  // NOT a theme token: --a-canvas-solid is a property of the VIEWER, and baking one
  // into a PDF would print the editor's grey onto a white slide.
  assert.deepStrictEqual(halo.stroke, parsePaint(WIRE_HALO_INK));
});

check("WIRES ARE NOT WIDGETS still holds after they became scene content", () => {
  // The document is the assertion: emitting a picture for a connection must not add
  // an item, and the node count out of derive must not change.
  const items = trio();
  const before = JSON.stringify(items);
  const nodes = deriveRenderTree({ items }, registry);
  sceneIR(nodes);
  assert.strictEqual(JSON.stringify(items), before, "emitting wires must not mutate the document");
  assert.strictEqual(nodes.length, 4, "four items in, four nodes out — wires are still not widgets");
});

check("a document with NO nodes emits not one wire op (every existing deck is byte-identical)", () => {
  const ir = sceneIR(deriveRenderTree({ items: { r: { type: "rect", x: 0, y: 0, w: 10, h: 10 } } }, registry));
  assert.strictEqual(ir.filter((o) => o.op === "path" && String(o.d).startsWith("M ")).length, 0);
});

check("CULLING MAY NOT EAT A WIRE: ctx.wireNodes keeps a half-offscreen patch's cables", () => {
  // THE DEFECT THIS PINS: only PresentMode culls, and it culls to the camera rect. A
  // wire from an off-camera SOURCE into an on-camera SINK is visible for most of its
  // length — deriving wires from the culled list would silently delete it, so the
  // presenter would draw a different picture than the PDF export of the same slide.
  const nodes = deriveRenderTree({ items: trio() }, registry);
  const culled = nodes.filter((n) => n.itemId !== "src"); // pretend `src` fell off the camera
  const wireOpsIn = (ir) => ir.filter((o) => o.op === "path" && String(o.d).startsWith("M ")).length;
  assert.strictEqual(wireOpsIn(sceneIR(culled)), 4,
    "without the pre-cull tree, src's wire is gone — this is the number the defect produced");
  assert.strictEqual(wireOpsIn(sceneIR(culled, { wireNodes: nodes })), 6,
    "with the pre-cull tree, all three wires survive while only the visible cards paint");
});

// ── WORKSTREAM BU: INPUTS ARE PROPERTIES, AND "node" IS A TYPE ───────────────
//
// The user's ruling, 2026-08-03: "none of these nodes seem to record any of their
// inputs as properties. Their inputs should all be properties. ... The wires are
// drawn by the receiver node, based on the equation given for where its source
// output is. ... Objects should be referenceable as equations and should be nodes.
// It's a different type than just float."

check("BU: every declared input port surfaces as a first-class Inspector row", () => {
  // THE DEFECT: an audio node's inputs map was invisible in the properties panel,
  // so the panel asserted BY OMISSION that a Filter had no wiring.
  const rows = nodeInputRows(registry.get("node_math"));
  assert.deepStrictEqual(rows.map((r) => r.key), ["inputs.a", "inputs.b"]);
  assert.ok(rows.every((r) => r.kind === NODE_INPUT_ROW_KIND), "each row declares the node-input control kind");
  assert.ok(rows.every((r) => r.portType === "number"), "and carries its port TYPE, which is what filters the picker");
  // The row's key is the ORDINARY state path the wire is stored at — that is the
  // whole mechanism: keyframing, undo and "=" come from it being ordinary.
  assert.deepStrictEqual(connectPairs({ item: "s", port: "out" }, { item: "m", port: "a" })[0][0].slice(2).join("."), rows[0].key);
});

check("BU: an input row renders honestly for UNWIRED and for WIRED", () => {
  const items = { n: { type: "node_number", name: "Speed" }, m: { type: "node_math" } };
  assert.strictEqual(nodeInputLabel(items, null), "", "unwired reads EMPTY, not a fake source");
  assert.strictEqual(nodeInputLabel(items, { item: "n", port: "out" }), "Speed › out", "wired names the source AND the port");
  // The label is re-derived from the item's CURRENT name, never stored, so a
  // rename cannot leave the row disagreeing with the wire on the canvas.
  assert.strictEqual(nodeInputLabel({ n: { ...items.n, name: "Tempo" } }, { item: "n", port: "out" }), "Tempo › out");
});

check("BU: the picker offers exactly what the WIRE DRAG would accept — no more, no less", () => {
  // It routes through connectionRefusal rather than re-deciding legality, so the
  // dropdown and the bead cannot drift into disagreeing about what is connectable.
  const items = trio();
  const forMulA = compatibleSources(items, registry, { item: "mul", port: "a" }).map((o) => `${o.item}.${o.port}`);
  assert.ok(forMulA.includes("src.out"), "a legal number source is offered");
  assert.ok(!forMulA.includes("mul.out"), "a node's own output is NOT offered to its own input (that is a cycle)");
  assert.ok(!forMulA.includes("disp.out"), "and neither is a downstream node, for the same reason");
  for (const o of compatibleSources(items, registry, { item: "mul", port: "a" }))
    assert.strictEqual(connectionRefusal(items, registry, { item: o.item, port: o.port }, { item: "mul", port: "a" }), null,
      `the picker offered ${o.item}.${o.port}, which connectionRefusal would refuse — the two surfaces have drifted`);
});

check("BU: the `node` port type exists, and has NO coercions in either direction", () => {
  assert.ok(PORT_TYPE_NAMES.includes("node"), "the user's node type is declared");
  assert.strictEqual(portZero("node"), null, "its zero is ABSENCE, not 0 — there is no identity item");
  // Not an omission: node carries an IDENTITY, not a value, so every pair would be
  // a category error (node→number is a DEREFERENCE the graph's own edge does).
  for (const other of PORT_TYPE_NAMES.filter((t) => t !== "node")) {
    assert.ok(!typesCompatible("node", other), `node→${other} must stay refused`);
    assert.ok(!typesCompatible(other, "node"), `${other}→node must stay refused`);
  }
  assert.ok(typesCompatible("node", "node"), "identity is still allowed, with no table entry");
});

check("BU: an EQUATION-DRIVEN input draws the SAME WIRE as a drag-authored one", () => {
  // THE USER'S RULING, mechanically: "the wires are drawn by the receiver node,
  // based on the equation given for where its source output is."
  //
  // It holds because evaluateState runs BEFORE deriveRenderTree, so an equation has
  // already become a plain {item, port} literal by the time deriveWires reads it.
  // BN's wire derivation needed NO change — that is what this pin protects.
  const mk = (v) => ({ items: {
    cam: { type: "camera", x: 0, y: 0, w: 1280, h: 720 },
    src: { type: "node_number", name: "Speed", x: 0, y: 0, w: 130, h: 90, value: 3 },
    disp: { type: "node_display", x: 400, y: 0, w: 140, h: 90, inputs: { in: v } },
  }, vars: {} });
  const wiresFor = (v) => deriveWires(deriveRenderTree(evaluateState(mk(v), registry).state, registry));
  const literal = wiresFor({ item: "src", port: "out" });
  assert.strictEqual(literal.length, 1, "the drag-authored wire is the control");
  assert.deepStrictEqual(wiresFor("= speed"), literal, "a BARE SLUG equation draws a byte-identical wire");
  assert.deepStrictEqual(wiresFor("= speed.out"), literal, "and so does one naming the port explicitly");
});

check("BU: an equation-driven input KEYFRAMES across slides like any other property", () => {
  // The ruling's stated reason for making inputs properties at all: "if we don't do
  // that we can't keyframe them." An EQUATION in the slot must keyframe too.
  const doc = {
    meta: { slideW: 1280, slideH: 720 },
    slides: [
      { id: "s0", name: "one", delta: { items: {
        cam: { type: "camera", x: 0, y: 0, w: 1280, h: 720 },
        src: { type: "node_number", name: "Three", x: 0, y: 0, w: 130, h: 90, value: 3 },
        two: { type: "node_number", name: "Two", x: 0, y: 200, w: 130, h: 90, value: 2 },
        disp: { type: "node_display", x: 400, y: 0, w: 140, h: 90, inputs: { in: "= three" } },
      } } },
      { id: "s1", name: "two", delta: { items: { disp: { inputs: { in: "= two" } } } } },
    ],
  };
  const at = (i) => evaluateNodeGraph(evaluateState(foldState(doc, i, 1), registry).state.items, registry).values.disp.inputs.in;
  assert.strictEqual(at(0), 3, "slide 0's equation resolves to the source of 3");
  assert.strictEqual(at(1), 2, "slide 1 REWIRED it by equation alone");
});

check("BU: a DANGLING reference is LOUD, and falls back to UNWIRED — never to 0", () => {
  const mk = (v) => ({ items: {
    src: { type: "node_number", name: "Speed", value: 3 },
    disp: { type: "node_display", inputs: { in: v } },
  }, vars: {} });
  for (const [src, why] of [
    ["= nope", /Unknown widget/],
    ["= speed.wrong", /has no output named/],
    ['= "speed"', /is not a node reference/],
    ["= 3", /is not a node reference/],
  ]) {
    const { state, errors } = evaluateState(mk(src), registry);
    assert.match(errors.get("items.disp.inputs.in") ?? "", why, `${src} must report its own reason`);
    // AND THE FALLBACK IS null. A 0 here is skipped by connectionsOf and
    // deriveWires alike, so the wire would vanish with no explanation — which is
    // indistinguishable from a deliberate disconnect. (This was real: the generic
    // `?? 0` fallback produced exactly that before fallbackFor learned the path.)
    assert.strictEqual(state.items.disp.inputs.in, null, `${src} must fall back to UNWIRED, not to a number`);
  }
});

check("BU: CLONE SEMANTICS — a literal wire remaps, an equation keeps pointing where it was written", () => {
  // THE HONEST BOUNDARY, measured rather than assumed. itemRefs' wildcard names
  // `inputs.*.item`, which is a LEAF of the literal — it cannot reach inside an
  // equation STRING, and pretending otherwise would be silent wrongness.
  assert.deepStrictEqual(NODE_ITEM_REFS, [["inputs", "*", "item"]], "the wildcard names the literal's leaf");
  // And the reason the equation half is a DECISION, not an oversight: slugs are
  // disambiguated per document, so a duplicated "Osc1" becomes `osc1_2` while the
  // copied equation text still says `osc1` — i.e. THE ORIGINAL. That is what an
  // equation MEANS ("whatever the document calls osc1"), and it is what makes one
  // shared source fanned across copies work for free.
  const slugs = slugMap({ items: { aaaa: { type: "node_number", name: "Osc1" }, bbbb: { type: "node_number", name: "Osc1" } } });
  assert.strictEqual(slugs.toId.get("osc1"), "aaaa", "the ORIGINAL keeps the bare slug");
  assert.strictEqual(slugs.toSlug.get("bbbb"), "osc1_2", "and the copy is disambiguated, so it is NOT what `= osc1` reads");
});

// ── SUMMARY ──────────────────────────────────────────────────────────────────

console.log(`nodeflow: ${pass} passed, ${fails.length} failed`);
for (const f of fails) console.error(`  FAIL ${f}`);
process.exit(fails.length ? 1 : 0);
