/**
 * The image-widget test fixture as a base64 PNG data URI — the exact form
 * the image plugin stores in state.src. Auto-generated by
 * scratchpad_agent_8.py (a 64x48 four-quadrant + white-diagonal pattern:
 * red TL / green TR / blue BL / amber BR, so parity catches any flip,
 * rotation, or channel swap and a human/VLM can read orientation at a
 * glance). Committed so tests/parity/CLI have an offline asset with no
 * asset-server dependency. The matching binary is checker.png.
 */

export const CHECKER_W = 64;
export const CHECKER_H = 48;
export const CHECKER_PNG_DATA_URI = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAAAwCAIAAAAuKetIAAAA/ElEQVR42tXSsQ3DMAxEUU2TNoB3TBFkggySRVxnF8dlAFuyRB3JO4G98PCvbH/vu9zh93gX1yvb4ckDsAZ3wP6HqyECUDNAGEEAP0McoMFQAsBTJACwhhwAcE6ZAEiKZMC8IR8wOScWgDkFEcBm4AIY5sQIGEpBCuhPQQ3oMbADLuckAGinkAHUDEqAxpxkAPEpyu21etyp4fMs8PMC1AxwhiMgJoU7YP/D1RABqBkgjCBAg6EE8DBEA+BzSgBgU6QBUCkyARBDMmB+ThSAmRQsALOBCGCbEx1gNAUjYMhACuifEzWgJwU74NIgAGjPSQZQMygBTg1igCPjB/R+uBMf7g2dAAAAAElFTkSuQmCC";
