/**
 * THE MODULE LIBRARY — the v1 module set, one factory each.
 *
 * COUNT: 23 modules, where the blueprint's MODULE SET v1 enumerates 22. The
 * extra one is `sampleHold`. It is not a deviation from intent: the blueprint's
 * IMPLEMENTATION LAW names "sample+hold" as one of the five required
 * AudioWorklet processors, but the module enumeration one paragraph later omits
 * it. Building the worklet and then not exposing a module for it would leave a
 * processor no patch could reach, so it is registered like the other 22. The
 * count is measured by tests/synth_engine_test.js, not asserted from here.
 *
 * ── THE UNIFORM SHAPE ────────────────────────────────────────────────────────
 * Every factory takes (context, params, resources) and returns:
 *
 *   {
 *     inputs:  { <portName>: AudioNode | AudioParam },   // where wires land
 *     outputs: { <portName>: AudioNode },                // where wires start
 *     params:  { <key>: AudioParam | setter },           // knobs
 *     start(): void,      // begin any oscillators (idempotent)
 *     dispose(): void,    // stop and release everything
 *     meta:    { kind, label, ... }
 *   }
 *
 * The engine NEVER special-cases a module type — it only ever looks up ports by
 * name and ramps gains around them. That uniformity is what makes glitch-free
 * rewiring one implementation rather than 22, and it is why adding a 23rd
 * module requires no engine change at all.
 *
 * ── NATIVE FIRST (blueprint, THE SYNTH ENGINE 2) ─────────────────────────────
 * 18 of the 23 modules are built ENTIRELY from native AudioNodes, which are C++
 * under the hood. Only 5 reach for an AudioWorklet, and each one's docstring
 * says which native node it would have used if one existed. The `IMPLEMENTATION`
 * constant below is the machine-readable version of that accounting, so the
 * claim is checkable rather than a comment that can rot.
 *
 * ── PARAM SETTERS AND WHY THEY ARE NOT ALL AudioParams ───────────────────────
 * Most knobs map to a real AudioParam, which gives sample-accurate ramping for
 * free. Some (an oscillator's waveform, a filter's type, a scale table) are
 * DISCRETE and have no AudioParam equivalent; those are exposed as plain setter
 * functions. The engine's setParam handles both, and `rampSeconds` is silently
 * meaningless for the discrete ones — documented per module rather than
 * pretending a waveform can crossfade.
 *
 * Zero PowerRP imports (the ENGINE law).
 */

import {
  clampParam,
  midiToFreq,
  bellVoice,
  supersawDetunes,
  MIN_AUDIBLE_HZ,
  MAX_AUDIBLE_HZ,
  BELL_PRESETS,
} from "./dsp.js";
import { DEFAULT_POLY_VOICES, MAX_POLY_VOICES, MIN_POLY_VOICES } from "./voices.js";

/**
 * Which modules are native-only and which need a worklet — the machine-readable
 * form of the implementation law, asserted by tests/synth_engine_test.js so the
 * "17 native / 5 worklet" claim cannot silently drift.
 */
export const IMPLEMENTATION = {
  output: "native",
  oscillator: "native",
  supersaw: "native",
  noise: "native",
  filter: "native",
  vca: "native",
  mixer: "native",
  lfo: "native",
  delay: "native",
  reverb: "native",
  eq3: "native",
  clock: "native",
  sequencer: "native",
  sampler: "native",
  meter: "native",
  spectrum: "native",
  ding: "native",
  pad: "native",
  polyPad: "native",
  adsr: "worklet",
  bitcrush: "worklet",
  quantize: "worklet",
  sampleHold: "worklet",
  trigger: "worklet",
};

// ─── Shared helpers ──────────────────────────────────────────────────────────

/**
 * Build a looping AudioBuffer of noise. Near-pure (allocates a buffer via the
 * context; deterministic given the same seed).
 *
 * WHY A BUFFER AND NOT A WORKLET: a noise worklet would burn a whole audio
 * thread slot to do what a looping BufferSource does in C++. The loop is long
 * enough (NOISE_SECONDS) that the repetition is not perceptible as a pattern.
 *
 * PINK vs WHITE: white noise has equal energy per Hz and sounds hissy and
 * top-heavy; pink has equal energy per OCTAVE, which matches how hearing works
 * and is what actually sounds like wind, surf, or a room. Pink is generated by
 * the Voss-McCartney-style filter cascade below — the standard cheap
 * approximation of a -3 dB/octave slope.
 */
function createNoiseBuffer(context, color, seed) {
  const length = Math.floor(NOISE_SECONDS * context.sampleRate);
  const buffer = context.createBuffer(1, length, context.sampleRate);
  const data = buffer.getChannelData(0);

  // Seeded so a patch's noise bed is reproducible across reloads.
  let state = seed >>> 0 || 1;
  const nextRandom = () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return ((state >>> 0) / 4294967296) * 2 - 1;
  };

  if (color === "white") {
    for (let i = 0; i < length; i++) data[i] = nextRandom();
  } else {
    // Paul Kellet's pink-noise filter cascade: six one-pole filters summed,
    // approximating -3 dB/octave to within 0.05 dB across the audible band.
    let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
    for (let i = 0; i < length; i++) {
      const white = nextRandom();
      b0 = 0.99886 * b0 + white * 0.0555179;
      b1 = 0.99332 * b1 + white * 0.0750759;
      b2 = 0.969 * b2 + white * 0.153852;
      b3 = 0.8665 * b3 + white * 0.3104856;
      b4 = 0.55 * b4 + white * 0.5329522;
      b5 = -0.7616 * b5 - white * 0.016898;
      data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * PINK_GAIN_TRIM;
      b6 = white * 0.115926;
    }
  }
  return buffer;
}

/** Long enough that the loop point is not heard as a rhythm. */
const NOISE_SECONDS = 4;

/** The Kellet cascade sums to roughly 3x unity; trims back to ~±1. */
const PINK_GAIN_TRIM = 0.11;

/**
 * A constant-signal source: a DC offset of 1.0 that any gain can scale.
 *
 * This is the standard Web Audio idiom for "a number as a signal" — it is what
 * lets a knob value be WIRED into an AudioParam and summed with modulation,
 * which is the whole basis of the modular paradigm.
 */
function createConstant(context, value) {
  const constant = context.createConstantSource();
  constant.offset.value = value;
  return constant;
}

// ─── 1. Output ───────────────────────────────────────────────────────────────

/**
 * OUTPUT — the terminal module: master volume, a limiter, and the tap the
 * engine's master meter reads.
 *
 * THE LIMITER IS NOT OPTIONAL. A modular patch can trivially sum six oscillators
 * into clipping, and digital clipping is harsh and can be genuinely painful in
 * headphones. A DynamicsCompressor with a high ratio and a low threshold acts as
 * a safety limiter that is inaudible until something is too loud. Native, so it
 * costs nothing.
 */
function outputModule(context, params, resources) {
  const input = context.createGain();
  const volume = context.createGain();
  const limiter = context.createDynamicsCompressor();

  volume.gain.value = clampParam(params.volume ?? 0.7, 0, 1, "volume");
  limiter.threshold.value = LIMITER_THRESHOLD_DB;
  limiter.knee.value = LIMITER_KNEE_DB;
  limiter.ratio.value = LIMITER_RATIO;
  limiter.attack.value = LIMITER_ATTACK_SECONDS;
  limiter.release.value = LIMITER_RELEASE_SECONDS;

  input.connect(volume);
  volume.connect(limiter);
  // THE ENGINE'S MASTER BUS, NOT `context.destination` (R7-22). Every output
  // module lands on one node, which is what gives the session a single place to
  // mute and a single place to record. Required, never defaulted: an output wired
  // straight to the destination would be audible while the rest of the patch was
  // muted, and invisible to a recorder — a silent-but-plausible failure in both
  // directions, which is exactly the class this codebase refuses to paper over.
  if (!resources?.destination) {
    throw new Error("outputModule: resources.destination (the engine's master bus) is required — see the master-chain block in synth/engine.js");
  }
  limiter.connect(resources.destination);

  return {
    inputs: { in: input },
    outputs: {},
    params: { volume: volume.gain },
    tap: limiter,
    start() {},
    dispose() {
      input.disconnect();
      volume.disconnect();
      limiter.disconnect();
    },
    meta: { kind: "output", label: "Output" },
  };
}

const LIMITER_THRESHOLD_DB = -6;
const LIMITER_KNEE_DB = 3;
const LIMITER_RATIO = 12;
const LIMITER_ATTACK_SECONDS = 0.003;
const LIMITER_RELEASE_SECONDS = 0.25;

// ─── 2. Oscillator ───────────────────────────────────────────────────────────

/**
 * OSCILLATOR — sine/triangle/sawtooth/square with detune. Pure native
 * OscillatorNode, which is band-limited in C++ (so no aliasing, and no need for
 * the PolyBLEP the research describes for a hand-rolled one).
 *
 * `frequency` and `detune` are AudioParams, so they accept wires as well as
 * knob values — that is how an LFO or envelope modulates pitch.
 * `waveform` is DISCRETE (a setter, not an AudioParam): rampSeconds is
 * meaningless for it and is ignored.
 */
function oscillatorModule(context, params) {
  const oscillator = context.createOscillator();
  const output = context.createGain();

  oscillator.type = params.waveform ?? "sine";
  oscillator.frequency.value = clampParam(params.frequency ?? 220, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
  oscillator.detune.value = clampParam(params.detune ?? 0, -MAX_DETUNE_CENTS, MAX_DETUNE_CENTS, "detune");
  output.gain.value = clampParam(params.level ?? 0.5, 0, 1, "level");
  oscillator.connect(output);

  let started = false;
  return {
    inputs: { frequency: oscillator.frequency, detune: oscillator.detune, level: output.gain },
    outputs: { out: output },
    params: {
      frequency: oscillator.frequency,
      detune: oscillator.detune,
      level: output.gain,
      waveform: (value) => {
        oscillator.type = value;
      },
    },
    start() {
      if (started) return;
      oscillator.start();
      started = true;
    },
    dispose() {
      if (started) oscillator.stop();
      oscillator.disconnect();
      output.disconnect();
    },
    meta: { kind: "oscillator", label: "Oscillator" },
  };
}

/** ±2 octaves of detune range, in cents. Beyond that, use frequency. */
const MAX_DETUNE_CENTS = 2400;

// ─── 3. Supersaw ─────────────────────────────────────────────────────────────

/**
 * SUPERSAW — a stack of detuned sawtooth oscillators, the raw material of the
 * ambience pad and the classic "huge" synth sound.
 *
 * The detune fan comes from dsp.supersawDetunes (pure, tested). Each voice is a
 * native OscillatorNode; the per-voice gain is 1/sqrt(n) rather than 1/n
 * because the voices are UNCORRELATED, so their amplitudes add in RMS (as the
 * square root) rather than linearly. Using 1/n would make an 7-voice stack
 * noticeably quieter than a 1-voice one.
 */
function supersawModule(context, params) {
  const output = context.createGain();
  const voiceCount = Math.max(1, Math.floor(params.voices ?? 7));
  const baseFrequency = clampParam(params.frequency ?? 110, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
  const detunes = supersawDetunes(voiceCount, params.spread ?? 14);

  output.gain.value = clampParam(params.level ?? 0.4, 0, 1, "level");

  const oscillators = detunes.map((cents) => {
    const oscillator = context.createOscillator();
    const voiceGain = context.createGain();
    oscillator.type = "sawtooth";
    oscillator.frequency.value = baseFrequency;
    oscillator.detune.value = cents;
    voiceGain.gain.value = 1 / Math.sqrt(voiceCount);
    oscillator.connect(voiceGain);
    voiceGain.connect(output);
    return oscillator;
  });

  let started = false;
  return {
    inputs: { level: output.gain },
    outputs: { out: output },
    params: {
      level: output.gain,
      // Frequency fans out to every voice, each keeping its own detune.
      frequency: (value, when, ramp) => {
        const target = clampParam(value, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
        for (const oscillator of oscillators) {
          if (ramp > 0) oscillator.frequency.setTargetAtTime(target, when, ramp);
          else oscillator.frequency.setValueAtTime(target, when);
        }
      },
      spread: (value) => {
        const nextDetunes = supersawDetunes(voiceCount, value);
        oscillators.forEach((oscillator, i) => {
          oscillator.detune.value = nextDetunes[i];
        });
      },
    },
    start() {
      if (started) return;
      for (const oscillator of oscillators) oscillator.start();
      started = true;
    },
    dispose() {
      for (const oscillator of oscillators) {
        if (started) oscillator.stop();
        oscillator.disconnect();
      }
      output.disconnect();
    },
    meta: { kind: "supersaw", label: "Supersaw" },
  };
}

// ─── 4. Noise ────────────────────────────────────────────────────────────────

/** NOISE — looping white or pink noise from a generated buffer (see
 * createNoiseBuffer for why buffer-not-worklet, and why pink matters). */
function noiseModule(context, params) {
  const source = context.createBufferSource();
  const output = context.createGain();

  source.buffer = createNoiseBuffer(context, params.color ?? "pink", params.seed ?? 1);
  source.loop = true;
  output.gain.value = clampParam(params.level ?? 0.3, 0, 1, "level");
  source.connect(output);

  let started = false;
  return {
    inputs: { level: output.gain },
    outputs: { out: output },
    params: { level: output.gain },
    start() {
      if (started) return;
      source.start();
      started = true;
    },
    dispose() {
      if (started) source.stop();
      source.disconnect();
      output.disconnect();
    },
    meta: { kind: "noise", label: "Noise" },
  };
}

// ─── 5. Filter ───────────────────────────────────────────────────────────────

/**
 * FILTER — native BiquadFilterNode: lowpass / highpass / bandpass / notch.
 *
 * This is the RBJ cookbook biquad the research rates "trivial, public domain" —
 * and the browser already ships it in C++, so writing our own would be strictly
 * worse. `frequency` and `Q` are AudioParams and therefore modulatable, which
 * is what makes the filter-sweep whoosh and the breathing pad possible.
 */
function filterModule(context, params) {
  const filter = context.createBiquadFilter();
  filter.type = params.type ?? "lowpass";
  filter.frequency.value = clampParam(params.frequency ?? 1200, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
  filter.Q.value = clampParam(params.Q ?? 1, MIN_FILTER_Q, MAX_FILTER_Q, "Q");

  return {
    inputs: { in: filter, frequency: filter.frequency, Q: filter.Q },
    outputs: { out: filter },
    params: {
      frequency: filter.frequency,
      Q: filter.Q,
      type: (value) => {
        filter.type = value;
      },
    },
    start() {},
    dispose() {
      filter.disconnect();
    },
    meta: { kind: "filter", label: "Filter" },
  };
}

/** Q below ~0.0001 is numerically unstable; above ~30 a biquad self-oscillates
 * into a painful sine. Both bounds are safety, not taste. */
const MIN_FILTER_Q = 0.0001;
const MAX_FILTER_Q = 30;

// ─── 6. ADSR (worklet) ───────────────────────────────────────────────────────

/**
 * ADSR — envelope with retrigger. WORKLET: see worklets/processors.js for why
 * native AudioParam automation cannot do a live retrigger correctly.
 *
 * Outputs a 0..1 control signal, meant to be wired into a VCA's gain or a
 * filter's frequency (via an attenuator gain to scale it into Hz).
 */
function adsrModule(context, params) {
  const node = new AudioWorkletNode(context, "adsr-processor", {
    numberOfInputs: 1,
    numberOfOutputs: 1,
    outputChannelCount: [1],
  });
  setWorkletParams(node, params, ["attack", "decay", "sustain", "release", "retrigger"]);

  return {
    inputs: {
      gate: node,
      attack: node.parameters.get("attack"),
      decay: node.parameters.get("decay"),
      sustain: node.parameters.get("sustain"),
      release: node.parameters.get("release"),
    },
    outputs: { out: node },
    params: {
      attack: node.parameters.get("attack"),
      decay: node.parameters.get("decay"),
      sustain: node.parameters.get("sustain"),
      release: node.parameters.get("release"),
      retrigger: node.parameters.get("retrigger"),
    },
    trigger() {
      node.port.postMessage({ type: "trigger" });
    },
    start() {},
    dispose() {
      node.disconnect();
    },
    meta: { kind: "adsr", label: "ADSR" },
  };
}

/** Apply any of `names` present in params to the worklet's AudioParams. */
function setWorkletParams(node, params, names) {
  for (const name of names) {
    if (params[name] === undefined) continue;
    const param = node.parameters.get(name);
    if (!param) throw new Error(`Worklet has no parameter ${JSON.stringify(name)}`);
    param.value = clampParam(params[name], param.minValue, param.maxValue, name);
  }
}

// ─── 7. VCA ──────────────────────────────────────────────────────────────────

/**
 * VCA — voltage-controlled amplifier: a gain whose level is wire-modulatable.
 *
 * The `gain` AudioParam is exposed as an INPUT port, which is the entire trick:
 * wiring an ADSR into it turns a drone into a played note. Web Audio sums all
 * connections into a param with its base value, so an envelope at 0..1 plus a
 * base of 0 gives exactly the envelope.
 */
function vcaModule(context, params) {
  const gain = context.createGain();
  gain.gain.value = clampParam(params.gain ?? 0, 0, MAX_VCA_GAIN, "gain");
  return {
    inputs: { in: gain, gain: gain.gain },
    outputs: { out: gain },
    params: { gain: gain.gain },
    start() {},
    dispose() {
      gain.disconnect();
    },
    meta: { kind: "vca", label: "VCA" },
  };
}

/** Above unity is allowed (a VCA can boost) but bounded so a runaway modulation
 * cannot produce a 1000x gain spike. */
const MAX_VCA_GAIN = 4;

// ─── 8. Mixer ────────────────────────────────────────────────────────────────

/**
 * MIXER — four inputs with individual levels, summed to one output.
 *
 * Web Audio sums implicitly when several nodes connect to one destination, so
 * the mixer is just four gains into a bus. Per-channel gains are AudioParams,
 * so channel levels are themselves modulatable (a crossfade is an LFO into two
 * channels in antiphase).
 */
function mixerModule(context, params) {
  const bus = context.createGain();
  bus.gain.value = clampParam(params.master ?? 1, 0, MAX_VCA_GAIN, "master");

  const inputs = {};
  const paramMap = { master: bus.gain };
  for (let channel = 1; channel <= MIXER_CHANNELS; channel++) {
    const gain = context.createGain();
    gain.gain.value = clampParam(params[`level${channel}`] ?? 0.7, 0, MAX_VCA_GAIN, `level${channel}`);
    gain.connect(bus);
    inputs[`in${channel}`] = gain;
    inputs[`level${channel}`] = gain.gain;
    paramMap[`level${channel}`] = gain.gain;
  }

  return {
    inputs,
    outputs: { out: bus },
    params: paramMap,
    start() {},
    dispose() {
      bus.disconnect();
    },
    meta: { kind: "mixer", label: "Mixer", channels: MIXER_CHANNELS },
  };
}

const MIXER_CHANNELS = 4;

// ─── 9. LFO ──────────────────────────────────────────────────────────────────

/**
 * LFO — a low-frequency oscillator with a DEPTH scaler.
 *
 * The depth gain is what makes an LFO usable: an OscillatorNode outputs ±1, but
 * modulating a filter cutoff needs ±800 Hz. So the output is
 * oscillator -> depth-gain, and `depth` is in the UNITS OF THE TARGET. Wiring
 * this to a filter's frequency with depth 800 sweeps ±800 Hz around the
 * filter's own base value.
 *
 * `bipolar: false` adds a DC offset so the output swings 0..depth instead of
 * ±depth — needed when modulating something that must not go negative (a VCA).
 */
function lfoModule(context, params) {
  const oscillator = context.createOscillator();
  const depth = context.createGain();
  const output = context.createGain();

  oscillator.type = params.waveform ?? "sine";
  oscillator.frequency.value = clampParam(params.frequency ?? 0.2, MIN_LFO_HZ, MAX_LFO_HZ, "frequency");
  depth.gain.value = params.depth ?? 1;
  oscillator.connect(depth);
  depth.connect(output);

  // Unipolar mode: add a constant equal to the depth, so the sum is 0..2*depth
  // scaled back to 0..depth by halving the depth gain.
  let offsetSource = null;
  if (params.bipolar === false) {
    depth.gain.value = (params.depth ?? 1) / 2;
    offsetSource = createConstant(context, (params.depth ?? 1) / 2);
    offsetSource.connect(output);
  }

  let started = false;
  return {
    inputs: { frequency: oscillator.frequency, depth: depth.gain },
    outputs: { out: output },
    params: {
      frequency: oscillator.frequency,
      depth: depth.gain,
      waveform: (value) => {
        oscillator.type = value;
      },
    },
    start() {
      if (started) return;
      oscillator.start();
      if (offsetSource) offsetSource.start();
      started = true;
    },
    dispose() {
      if (started) {
        oscillator.stop();
        if (offsetSource) offsetSource.stop();
      }
      oscillator.disconnect();
      depth.disconnect();
      output.disconnect();
      if (offsetSource) offsetSource.disconnect();
    },
    meta: { kind: "lfo", label: "LFO" },
  };
}

/** An LFO is by definition sub-audio-rate at the low end; the top overlaps
 * audio rate deliberately, because audio-rate modulation is a valid effect. */
const MIN_LFO_HZ = 0.01;
const MAX_LFO_HZ = 200;

// ─── 10. Delay ───────────────────────────────────────────────────────────────

/**
 * DELAY / ECHO — a feedback delay with optional ping-pong stereo.
 *
 * Feedback is DAMPED by a lowpass inside the loop. Without it, an echo repeats
 * forever at identical brightness, which sounds artificial and can build up
 * into a howl; damping each pass is what makes repeats decay naturally into the
 * background, which is exactly the ambience use case.
 *
 * PING-PONG alternates repeats between the ears via a channel-swapped second
 * delay line, which widens the stereo image enormously for very little cost.
 */
function delayModule(context, params) {
  const input = context.createGain();
  const delayLeft = context.createDelay(MAX_DELAY_SECONDS);
  const delayRight = context.createDelay(MAX_DELAY_SECONDS);
  const feedback = context.createGain();
  const damping = context.createBiquadFilter();
  const wet = context.createGain();
  const dry = context.createGain();
  const output = context.createGain();
  const merger = context.createChannelMerger(2);

  const time = clampParam(params.time ?? 0.38, 0.001, MAX_DELAY_SECONDS, "time");
  delayLeft.delayTime.value = time;
  delayRight.delayTime.value = time;
  feedback.gain.value = clampParam(params.feedback ?? 0.35, 0, MAX_FEEDBACK, "feedback");
  damping.type = "lowpass";
  damping.frequency.value = clampParam(params.damping ?? 2600, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "damping");
  wet.gain.value = clampParam(params.wet ?? 0.35, 0, 1, "wet");
  dry.gain.value = clampParam(params.dry ?? 1, 0, 1, "dry");

  input.connect(dry);
  dry.connect(output);
  input.connect(delayLeft);

  if (params.pingPong === false) {
    delayLeft.connect(damping);
    damping.connect(feedback);
    feedback.connect(delayLeft);
    delayLeft.connect(wet);
  } else {
    // Left feeds right, right feeds back into left — repeats alternate ears.
    delayLeft.connect(delayRight);
    delayRight.connect(damping);
    damping.connect(feedback);
    feedback.connect(delayLeft);
    delayLeft.connect(merger, 0, 0);
    delayRight.connect(merger, 0, 1);
    merger.connect(wet);
  }
  wet.connect(output);

  return {
    inputs: { in: input, time: delayLeft.delayTime, feedback: feedback.gain },
    outputs: { out: output },
    params: {
      time: delayLeft.delayTime,
      feedback: feedback.gain,
      damping: damping.frequency,
      wet: wet.gain,
      dry: dry.gain,
    },
    start() {},
    dispose() {
      for (const node of [input, delayLeft, delayRight, feedback, damping, wet, dry, output, merger]) {
        node.disconnect();
      }
    },
    meta: { kind: "delay", label: "Delay" },
  };
}

const MAX_DELAY_SECONDS = 4;

/** Feedback >= 1 is a runaway that grows without bound. 0.95 is "very long
 * tail" while still strictly decaying. */
const MAX_FEEDBACK = 0.95;

// ─── 11. Reverb ──────────────────────────────────────────────────────────────

/**
 * REVERB — native ConvolverNode with a GENERATED impulse response.
 *
 * The IR comes from dsp.generateImpulseResponse (pure, seeded, tested) and is
 * turned into an AudioBuffer here — that split is why the reverb's character is
 * provable in bare node while the convolution itself runs in optimized C++.
 * No binary assets, per the blueprint.
 *
 * `character` is DISCRETE (hall / plate / deepSpace); changing it swaps the
 * buffer, which the engine does under a gain ramp like any other topology
 * change, because swapping a convolver's buffer mid-tail is otherwise a click.
 */
function reverbModule(context, params, resources) {
  const input = context.createGain();
  const convolver = context.createConvolver();
  const wet = context.createGain();
  const dry = context.createGain();
  const output = context.createGain();
  const preDelay = context.createDelay(MAX_PREDELAY_SECONDS);

  convolver.normalize = true;
  convolver.buffer = resources.impulseResponse(params.character ?? "hall");
  preDelay.delayTime.value = clampParam(params.preDelay ?? 0.01, 0, MAX_PREDELAY_SECONDS, "preDelay");
  wet.gain.value = clampParam(params.wet ?? 0.5, 0, 1, "wet");
  dry.gain.value = clampParam(params.dry ?? 0.6, 0, 1, "dry");

  input.connect(dry);
  dry.connect(output);
  input.connect(preDelay);
  preDelay.connect(convolver);
  convolver.connect(wet);
  wet.connect(output);

  return {
    inputs: { in: input, wet: wet.gain },
    outputs: { out: output },
    params: {
      wet: wet.gain,
      dry: dry.gain,
      preDelay: preDelay.delayTime,
      character: (value) => {
        convolver.buffer = resources.impulseResponse(value);
      },
    },
    start() {},
    dispose() {
      for (const node of [input, convolver, wet, dry, output, preDelay]) node.disconnect();
    },
    meta: { kind: "reverb", label: "Reverb" },
  };
}

const MAX_PREDELAY_SECONDS = 0.2;

// ─── 12-15. Worklet effects ──────────────────────────────────────────────────

/** BITCRUSH — WORKLET (no native decimator; WaveShaper can quantize amplitude
 * but cannot hold samples in time). See worklets/processors.js. */
function bitcrushModule(context, params) {
  const node = new AudioWorkletNode(context, "bitcrush-processor");
  setWorkletParams(node, params, ["bits", "reduction"]);
  return {
    inputs: { in: node, bits: node.parameters.get("bits"), reduction: node.parameters.get("reduction") },
    outputs: { out: node },
    params: { bits: node.parameters.get("bits"), reduction: node.parameters.get("reduction") },
    start() {},
    dispose() {
      node.disconnect();
    },
    meta: { kind: "bitcrush", label: "Bitcrush" },
  };
}

/** QUANTIZE — WORKLET (musical scale snapping has no native equivalent).
 * `scale` is DISCRETE: an array of semitone offsets, set by message. */
function quantizeModule(context, params) {
  const node = new AudioWorkletNode(context, "quantize-processor");
  setWorkletParams(node, params, ["range"]);
  if (params.scale) node.port.postMessage({ scale: params.scale });
  return {
    inputs: { in: node },
    outputs: { out: node },
    params: {
      range: node.parameters.get("range"),
      scale: (value) => node.port.postMessage({ scale: value }),
    },
    start() {},
    dispose() {
      node.disconnect();
    },
    meta: { kind: "quantize", label: "Quantize" },
  };
}

/** SAMPLE & HOLD — WORKLET. Input 0 = signal, input 1 = trigger. */
function sampleHoldModule(context) {
  const node = new AudioWorkletNode(context, "sample-hold-processor", {
    numberOfInputs: 2,
    numberOfOutputs: 1,
    outputChannelCount: [1],
  });
  return {
    inputs: { in: { node, index: 0 }, trigger: { node, index: 1 } },
    outputs: { out: node },
    params: {},
    start() {},
    dispose() {
      node.disconnect();
    },
    meta: { kind: "sampleHold", label: "Sample & Hold" },
  };
}

/** RISING-EDGE TRIGGER — WORKLET. The Axoloti ruling; Schmitt hysteresis. */
function triggerModule(context, params, resources, onFired) {
  const node = new AudioWorkletNode(context, "trigger-processor");
  setWorkletParams(node, params, ["pulseMs"]);
  node.port.onmessage = (event) => {
    if (event.data && event.data.type === "fired" && onFired) onFired();
  };
  return {
    inputs: { in: node },
    outputs: { out: node },
    params: { pulseMs: node.parameters.get("pulseMs") },
    start() {},
    dispose() {
      node.port.onmessage = null;
      node.disconnect();
    },
    meta: { kind: "trigger", label: "Trigger" },
  };
}

// ─── 16. EQ3 ─────────────────────────────────────────────────────────────────

/**
 * EQ3 — three-band shelf/peak EQ from native biquads in series.
 *
 * The full draggable-response parametric EQ is wave 2 per the blueprint; this
 * is the honest three-knob version. Low shelf, mid peaking, high shelf is the
 * standard console layout and is enough to sculpt a pad into the background,
 * which is the ambience use case that matters now.
 */
function eq3Module(context, params) {
  const low = context.createBiquadFilter();
  const mid = context.createBiquadFilter();
  const high = context.createBiquadFilter();

  low.type = "lowshelf";
  low.frequency.value = params.lowFrequency ?? 220;
  low.gain.value = clampParam(params.low ?? 0, MIN_EQ_DB, MAX_EQ_DB, "low");

  mid.type = "peaking";
  mid.frequency.value = params.midFrequency ?? 1000;
  mid.Q.value = params.midQ ?? 0.8;
  mid.gain.value = clampParam(params.mid ?? 0, MIN_EQ_DB, MAX_EQ_DB, "mid");

  high.type = "highshelf";
  high.frequency.value = params.highFrequency ?? 3600;
  high.gain.value = clampParam(params.high ?? 0, MIN_EQ_DB, MAX_EQ_DB, "high");

  low.connect(mid);
  mid.connect(high);

  return {
    inputs: { in: low },
    outputs: { out: high },
    params: {
      low: low.gain,
      mid: mid.gain,
      high: high.gain,
      lowFrequency: low.frequency,
      midFrequency: mid.frequency,
      highFrequency: high.frequency,
      midQ: mid.Q,
    },
    start() {},
    dispose() {
      low.disconnect();
      mid.disconnect();
      high.disconnect();
    },
    meta: { kind: "eq3", label: "EQ3" },
  };
}

const MIN_EQ_DB = -24;
const MAX_EQ_DB = 24;

// ─── 17-18. Clock and sequencer ──────────────────────────────────────────────

/**
 * CLOCK — a BPM source. Emits a pulse train on its output AND drives the
 * engine's scheduler.
 *
 * The audible/wireable pulse is a native oscillator shaped into a pulse by a
 * WaveShaper; the SCHEDULING is done by the two-clock scheduler, not by this
 * signal. That split matters: a wire carries the clock to other MODULES, while
 * the scheduler carries it to EVENTS, and the latter has to be sample-accurate
 * in a way a signal path cannot express.
 */
function clockModule(context, params) {
  const oscillator = context.createOscillator();
  const shaper = context.createWaveShaper();
  const output = context.createGain();

  const bpm = clampParam(params.bpm ?? 90, 20, 300, "bpm");
  oscillator.type = "square";
  oscillator.frequency.value = (bpm / 60) * (params.stepsPerBeat ?? 4);
  // Map the square's -1..1 to a clean 0..1 gate: everything below 0 -> 0.
  shaper.curve = gateCurve();
  oscillator.connect(shaper);
  shaper.connect(output);

  let started = false;
  return {
    inputs: {},
    outputs: { out: output },
    params: { frequency: oscillator.frequency },
    start() {
      if (started) return;
      oscillator.start();
      started = true;
    },
    dispose() {
      if (started) oscillator.stop();
      oscillator.disconnect();
      shaper.disconnect();
      output.disconnect();
    },
    meta: { kind: "clock", label: "Clock", bpm },
  };
}

/** A 2-point curve mapping negatives to 0 and positives to 1 — the cheapest
 * bipolar-to-unipolar gate conversion, and it runs in C++. */
function gateCurve() {
  const curve = new Float32Array(GATE_CURVE_POINTS);
  for (let i = 0; i < GATE_CURVE_POINTS; i++) {
    curve[i] = i < GATE_CURVE_POINTS / 2 ? 0 : 1;
  }
  return curve;
}

const GATE_CURVE_POINTS = 256;

/**
 * SEQUENCER — 16 steps of pitch + gate, driven by the engine's scheduler.
 *
 * The module itself owns only the PATTERN and a control-signal output; the
 * timing comes from the shared scheduler, so every sequencer in a patch is
 * locked to one transport. Step events are delivered to the engine, which fires
 * them at their scheduled audio-clock time.
 */
function sequencerModule(context, params) {
  const pitchOutput = createConstant(context, 0);
  const gateOutput = context.createGain();
  const gateSource = createConstant(context, 0);
  gateSource.connect(gateOutput);

  const steps = normalizeSteps(params.steps, params.stepCount ?? DEFAULT_SEQUENCER_STEPS);

  let started = false;
  return {
    inputs: {},
    outputs: { pitch: pitchOutput, gate: gateOutput },
    params: {
      steps: (value) => {
        const next = normalizeSteps(value, steps.length);
        for (let i = 0; i < steps.length; i++) steps[i] = next[i];
      },
    },
    /**
     * Command. Play one step at an audio-clock time. Called by the engine from
     * the scheduler, never from a timer directly — that is what makes the
     * timing sample-accurate.
     */
    playStep(index, time) {
      const step = steps[index % steps.length];
      if (!step || !step.on) return;
      const hz = midiToFreq(step.note);
      pitchOutput.offset.setValueAtTime(hz, time);
      // AND AS A PLAIN NUMBER, for whoever is STRUCK by this step (WORKSTREAM CC).
      // A scheduled setValueAtTime does NOT move `offset.value` — measured — so a
      // module reading the param on the control thread sees the pitch it had
      // BEFORE this step, which for a patch whose pitch comes only from the wire
      // is the initial 0. That is why Gamelan Bells played its whole melody at the
      // 20 Hz clamp. `controlValue` is the same number, readable where a discrete
      // strike is decided; the AudioParam remains the thing an audio-rate consumer
      // is connected to, so the wire's audio-thread behaviour is unchanged.
      pitchOutput.controlValue = hz;
      // A short gate pulse: up at `time`, down a moment later. The receiving
      // ADSR's Schmitt detector sees a clean rising edge.
      gateSource.offset.setValueAtTime(1, time);
      gateSource.offset.setValueAtTime(0, time + SEQUENCER_GATE_SECONDS);
    },
    start() {
      if (started) return;
      pitchOutput.start();
      gateSource.start();
      started = true;
    },
    dispose() {
      if (started) {
        pitchOutput.stop();
        gateSource.stop();
      }
      pitchOutput.disconnect();
      gateSource.disconnect();
      gateOutput.disconnect();
    },
    meta: { kind: "sequencer", label: "Sequencer", stepCount: steps.length },
  };
}

/** Coerce a pattern into a full-length array of {on, note} — a short or sparse
 * pattern is padded with rests rather than throwing, because a partially
 * authored pattern is a normal editing state, not an error. */
function normalizeSteps(steps, count) {
  const normalized = [];
  for (let i = 0; i < count; i++) {
    const step = steps && steps[i];
    if (typeof step === "number") normalized.push({ on: true, note: step });
    else if (step && typeof step === "object") normalized.push({ on: step.on !== false, note: step.note ?? 60 });
    else normalized.push({ on: false, note: 60 });
  }
  return normalized;
}

const DEFAULT_SEQUENCER_STEPS = 16;

/** Long enough for a Schmitt detector to see a clean edge, short enough to read
 * as a trigger rather than a sustained gate. */
const SEQUENCER_GATE_SECONDS = 0.02;

// ─── 19. Sampler ─────────────────────────────────────────────────────────────

/**
 * SAMPLER / LOOPER — plays an AudioBuffer, optionally seamlessly looped.
 *
 * The buffer is supplied by the host (PowerRP will hand it a decoded asset);
 * the module never fetches, because a synth module doing network I/O would be
 * exactly the ephemeral state the architecture forbids.
 *
 * Loop points default to the whole buffer. The research's seamless-loop rule
 * (zero-crossing boundaries) is the ASSET's responsibility — we expose
 * loopStart/loopEnd so a caller can honor it.
 */
function samplerModule(context, params) {
  const output = context.createGain();
  output.gain.value = clampParam(params.level ?? 0.8, 0, 1, "level");

  let source = null;
  let started = false;
  const buffer = params.buffer ?? null;

  function build() {
    source = context.createBufferSource();
    source.buffer = buffer;
    source.loop = params.loop !== false;
    if (params.loopStart !== undefined) source.loopStart = params.loopStart;
    if (params.loopEnd !== undefined) source.loopEnd = params.loopEnd;
    source.playbackRate.value = clampParam(params.rate ?? 1, MIN_PLAYBACK_RATE, MAX_PLAYBACK_RATE, "rate");
    source.connect(output);
  }

  return {
    inputs: { level: output.gain },
    outputs: { out: output },
    params: {
      level: output.gain,
      rate: (value) => {
        if (source) source.playbackRate.value = clampParam(value, MIN_PLAYBACK_RATE, MAX_PLAYBACK_RATE, "rate");
      },
    },
    start() {
      if (started || !buffer) return;
      build();
      source.start();
      started = true;
    },
    dispose() {
      if (source) {
        if (started) source.stop();
        source.disconnect();
      }
      output.disconnect();
    },
    meta: { kind: "sampler", label: "Sampler" },
  };
}

const MIN_PLAYBACK_RATE = 0.05;
const MAX_PLAYBACK_RATE = 8;

// ─── 20-21. Analysis taps ────────────────────────────────────────────────────

/**
 * METER — a level tap. Passes audio through UNCHANGED and exposes an
 * AnalyserNode the engine polls for RMS.
 *
 * Pass-through matters: a meter you have to branch to is a meter people forget
 * to wire. Inserting it in the signal path means the level shown is exactly
 * what flows onward.
 */
function meterModule(context) {
  const analyser = context.createAnalyser();
  analyser.fftSize = METER_FFT_SIZE;
  analyser.smoothingTimeConstant = METER_SMOOTHING;
  return {
    inputs: { in: analyser },
    outputs: { out: analyser },
    params: {},
    analyser,
    start() {},
    dispose() {
      analyser.disconnect();
    },
    meta: { kind: "meter", label: "Meter" },
  };
}

/** Small FFT: for RMS we only need time-domain data, and a small buffer keeps
 * the poll cheap at 60 fps. */
const METER_FFT_SIZE = 256;

/** Heavy smoothing so the needle is readable rather than twitchy. */
const METER_SMOOTHING = 0.8;

/** SPECTRUM — a frequency-analysis tap, also pass-through. Larger FFT than the
 * meter because frequency resolution is the whole point here. */
function spectrumModule(context, params) {
  const analyser = context.createAnalyser();
  analyser.fftSize = params.fftSize ?? SPECTRUM_FFT_SIZE;
  analyser.smoothingTimeConstant = params.smoothing ?? SPECTRUM_SMOOTHING;
  return {
    inputs: { in: analyser },
    outputs: { out: analyser },
    params: {},
    analyser,
    start() {},
    dispose() {
      analyser.disconnect();
    },
    meta: { kind: "spectrum", label: "Spectrum" },
  };
}

const SPECTRUM_FFT_SIZE = 2048;

/** Lighter than the meter's: a spectrum that smooths too hard stops showing
 * transients, which is when you most want to see it. */
const SPECTRUM_SMOOTHING = 0.72;

// ─── 22. METALLIC DING (wow module) ──────────────────────────────────────────

/**
 * METALLIC DING — an FM bell, and one of the two modules the user asked to be
 * genuinely beautiful.
 *
 * ── WHY FM AND NOT SUBTRACTIVE ───────────────────────────────────────────────
 * A bell's overtones are INHARMONIC — not integer multiples of the fundamental.
 * Subtractive synthesis starts from a harmonic waveform and can only remove;
 * it can never produce inharmonic partials, which is why filtered saws sound
 * like organs and never like bells. FM generates inharmonic sidebands directly
 * from a non-integer carrier:modulator ratio, which is why it has been THE bell
 * technique since Chowning in 1973.
 *
 * ── WHAT MAKES IT SOUND REAL (the details that matter) ───────────────────────
 * 1. THE MODULATION INDEX DECAYS FASTER THAN THE AMPLITUDE. This is the single
 *    most important one. A real bell is BRIGHT at the strike and PURE as it
 *    rings out — the high partials die first. If the index held constant, the
 *    result is a buzzer with a volume envelope. dsp.bellVoice enforces
 *    indexDecaySeconds < ampDecaySeconds by construction.
 * 2. EXPONENTIAL, NOT LINEAR, DECAY. Struck resonant objects lose energy
 *    proportionally to what they have, which is exponential. A linear fade
 *    sounds like someone turning a knob down.
 * 3. A TOUCH OF INHARMONIC SHIMMER. A second, quieter carrier at a slightly
 *    offset ratio beats against the first, which is what gives real bells their
 *    slow "wobble" as they ring. Without it the tail is sterile.
 * 4. THE STRIKE TRANSIENT. A very short filtered noise burst at onset supplies
 *    the "clank" of hammer-on-metal that pure FM lacks. It is brief enough
 *    (~12 ms) to read as part of the attack rather than as noise.
 *
 * Native throughout — oscillators, gains and an envelope drawn with AudioParam
 * automation. Nothing here needs a worklet, because the envelope is scheduled
 * ONCE per strike rather than retriggered live.
 */
function dingModule(context, params, resources) {
  const output = context.createGain();
  const preset = params.preset ?? "ding";
  if (!BELL_PRESETS[preset]) {
    throw new Error(
      `Unknown bell preset ${JSON.stringify(preset)}; expected one of ${Object.keys(BELL_PRESETS).join(", ")}`,
    );
  }
  output.gain.value = clampParam(params.level ?? 0.5, 0, 1, "level");

  // ── THE PITCH SEAM (wave 3): a WIRE-CONNECTABLE frequency, sampled at STRIKE ──
  //
  // The knob's value lives on a ConstantSourceNode's offset rather than in a
  // plain JS number, and `frequency` is that offset — which is what makes it an
  // ordinary AudioParam any control signal can be connected INTO. Web Audio sums
  // every connection into a param, so a sequencer's pitch output patched here
  // ADDS to the knob; the knob therefore reads as an OFFSET (set it to 0 and the
  // wire alone determines the pitch, set it to 220 and the wire transposes up
  // from there), which is the modular convention and the one that makes an
  // unpatched ding behave exactly as it did before this existed.
  //
  // ── WHY SAMPLED AT TRIGGER TIME AND NOT AUDIO-RATE ──────────────────────────
  // A struck bell is not a running oscillator being retuned: `trigger` builds a
  // fresh FM voice per strike (see below), and that voice's carrier/modulator
  // ratio is FIXED at construction because a bell's inharmonic partials are a
  // property of the object that was struck. Continuously sweeping a ringing
  // bell's pitch is not what a bell does — it is what a siren does. So the port
  // sets THE PITCH OF THE NEXT STRIKE, read here as `pitchBus.offset.value`.
  //
  // Reading `.value` is exact for this use and NOT an approximation of an
  // audio-rate read: `.value` returns the param's current computed value
  // including every connected input's contribution, and a strike is a single
  // instant, so there is nothing to average over. The one honest limitation is
  // that a source scheduled to change at a FUTURE time (a sequencer's
  // setValueAtTime for the next step) is not visible yet — which is exactly
  // right, because the strike being scheduled belongs to the step whose pitch is
  // current. This is why per-strike voice semantics are PRESERVED rather than
  // worked around.
  //
  // ── THE OFFSET IS NOT CLAMPED TO THE AUDIBLE BAND, AND THAT IS THE POINT ────
  // Every other frequency in this file is clamped to [MIN_AUDIBLE_HZ, …] at
  // construction, because it IS a pitch and a sub-audio pitch is an authoring
  // mistake worth catching. This one is an OFFSET that a wire sums into, and its
  // most useful value is ZERO — "the wire alone names the note", which is what a
  // sequenced melody wants. Clamping it to 20 Hz would silently detune every
  // note in that patch by 20 Hz and there would be nothing to see. What IS still
  // checked is finiteness (clampParam's own first job), across a range that
  // permits a negative offset — transposing DOWN is a legitimate patch.
  // The strike itself is clamped to the audible band, where it is a real pitch.
  const pitchBus = createConstant(context, clampParam(params.frequency ?? 880, -MAX_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency"));
  pitchBus.start();

  return {
    inputs: { level: output.gain, frequency: pitchBus.offset },
    outputs: { out: output },
    params: {
      level: output.gain,
      frequency: pitchBus.offset,
    },
    /**
     * Command. Strike the bell at an audio-clock time. Builds a fresh voice per
     * strike and disposes it on ended — bells are one-shot, so a persistent
     * voice would be wasted CPU between strikes, and per-strike voices give
     * free polyphony (overlapping rings).
     *
     * `options.frequency` (what engine.trigger passes through) still WINS over
     * the port, because it is a caller naming a pitch for one specific strike —
     * a patch's random-pitched gull — and that is more specific than a standing
     * wire. With neither, the knob's own offset is the pitch.
     */
    trigger(time = context.currentTime, options = {}) {
      // Out-of-range is CLAMPED rather than refused: unlike a knob (whose value
      // the author typed and whose mistake is worth a sentence), this number can
      // be the sum of a wire and an offset, and a modulation that briefly
      // overshoots must not throw on the audio path and kill the strike.
      const struckAt = options.frequency ?? Math.max(MIN_AUDIBLE_HZ, Math.min(MAX_AUDIBLE_HZ, pitchBus.offset.value));
      const voice = bellVoice(preset, struckAt);
      const carrier = context.createOscillator();
      const modulator = context.createOscillator();
      const modulationDepth = context.createGain();
      const amplitude = context.createGain();
      const shimmer = context.createOscillator();
      const shimmerGain = context.createGain();

      carrier.frequency.value = voice.carrierHz;
      modulator.frequency.value = voice.modulatorHz;

      // FM: the modulator's output, scaled to Hz, is ADDED to the carrier's
      // frequency. That addition is what Web Audio's param connection does.
      modulationDepth.gain.setValueAtTime(voice.modulationDepthHz, time);
      modulationDepth.gain.exponentialRampToValueAtTime(
        voice.modulationDepthHz * INDEX_FLOOR_FRACTION,
        time + voice.indexDecaySeconds,
      );
      modulator.connect(modulationDepth);
      modulationDepth.connect(carrier.frequency);

      // Detail 3: the shimmer partial, slightly off-ratio so it beats.
      shimmer.frequency.value = voice.carrierHz * SHIMMER_RATIO;
      shimmerGain.gain.value = SHIMMER_LEVEL;
      shimmer.connect(shimmerGain);
      shimmerGain.connect(amplitude);

      // Detail 2: exponential amplitude decay after a very fast attack.
      amplitude.gain.setValueAtTime(0, time);
      amplitude.gain.linearRampToValueAtTime(1, time + BELL_ATTACK_SECONDS);
      amplitude.gain.exponentialRampToValueAtTime(SILENCE_FLOOR, time + voice.ampDecaySeconds);

      carrier.connect(amplitude);
      amplitude.connect(output);

      // Detail 4: the strike transient.
      const strike = context.createBufferSource();
      const strikeFilter = context.createBiquadFilter();
      const strikeGain = context.createGain();
      strike.buffer = resources.strikeNoise();
      strikeFilter.type = "bandpass";
      strikeFilter.frequency.value = voice.carrierHz * STRIKE_BAND_RATIO;
      strikeFilter.Q.value = STRIKE_Q;
      strikeGain.gain.setValueAtTime(STRIKE_LEVEL, time);
      strikeGain.gain.exponentialRampToValueAtTime(SILENCE_FLOOR, time + STRIKE_SECONDS);
      strike.connect(strikeFilter);
      strikeFilter.connect(strikeGain);
      strikeGain.connect(output);

      const stopTime = time + voice.ampDecaySeconds + VOICE_TAIL_PADDING;
      for (const node of [carrier, modulator, shimmer, strike]) {
        node.start(time);
        node.stop(stopTime);
      }
      carrier.onended = () => {
        for (const node of [carrier, modulator, shimmer, strike, modulationDepth, amplitude, shimmerGain, strikeFilter, strikeGain]) {
          node.disconnect();
        }
      };
    },
    start() {},
    dispose() {
      // The pitch bus is a STARTED source, so it must be stopped as well as
      // disconnected — a running ConstantSourceNode keeps its whole graph alive
      // and the engine's leak check counts it.
      pitchBus.stop();
      pitchBus.disconnect();
      output.disconnect();
    },
    meta: { kind: "ding", label: "Metallic Ding", preset },
  };
}

/** exponentialRampToValueAtTime cannot reach 0 (it is undefined there), so
 * every decay targets this instead — 100 dB down, inaudible. */
const SILENCE_FLOOR = 0.0001;

/** The index decays TO this fraction of its peak, not to nothing: a bell's tail
 * keeps a little inharmonic content, and ramping to true silence sounds like
 * the timbre is being switched off. */
const INDEX_FLOOR_FRACTION = 0.02;

const BELL_ATTACK_SECONDS = 0.002;

/** Slightly sharp of a perfect fifth — deliberately NOT a simple ratio, so it
 * beats slowly against the carrier instead of locking into consonance. */
const SHIMMER_RATIO = 2.53;
const SHIMMER_LEVEL = 0.12;

const STRIKE_SECONDS = 0.012;
const STRIKE_LEVEL = 0.35;
const STRIKE_BAND_RATIO = 3.2;
const STRIKE_Q = 1.4;

/** Extra time before stopping a voice, so the exponential tail is not cut. */
const VOICE_TAIL_PADDING = 0.2;

// ─── 23. AMBIENCE PAD (wow module) ───────────────────────────────────────────

/**
 * AMBIENCE PAD — an entire spacey synth as ONE module, spacey by default.
 *
 * The user asked for "a module that's just an entire synth", and for the result
 * to sound like "whooshing around in space". This is that module: patch nothing
 * else, connect it to the output, and it is already the sound.
 *
 * ── THE SIGNAL CHAIN AND WHY EACH STAGE IS THERE ─────────────────────────────
 *   supersaw stack        — 7 detuned saws. The detuning beats at ~0.3-1 Hz,
 *                           which is the "alive, breathing" quality; a single
 *                           saw sounds thin and static no matter what follows.
 *   + sub sine            — one octave down, quiet. Supplies weight the saw
 *                           stack lacks; felt more than heard.
 *   -> lowpass filter     — tames the saws' harsh upper harmonics. Pads live
 *                           BEHIND things, and unfiltered saws fight the
 *                           foreground.
 *   <- slow LFO on cutoff — 0.06 Hz, ±700 Hz. THE motion. Slow enough to never
 *                           read as an effect, just as "the sound is moving".
 *                           This is the single most important stage for
 *                           avoiding listener fatigue over a long presentation.
 *   -> shimmer delay      — a long, heavily damped, ping-pong delay. Smears the
 *                           pad into a wash and widens it across the stereo
 *                           field.
 *   -> deep-space reverb  — the generated IR with a slow bloom. Puts it in a
 *                           very large room.
 *
 * Every stage is a native AudioNode. The whole module is ~14 nodes, which is
 * nothing — the browser runs them in C++.
 */
function padModule(context, params, resources) {
  const output = context.createGain();
  const voiceMix = context.createGain();
  const filter = context.createBiquadFilter();
  const lfo = context.createOscillator();
  const lfoDepth = context.createGain();
  const subOscillator = context.createOscillator();
  const subGain = context.createGain();

  const rootFrequency = clampParam(params.frequency ?? 82.4, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
  const detunes = supersawDetunes(params.voices ?? PAD_VOICES, params.spread ?? PAD_SPREAD_CENTS);

  output.gain.value = clampParam(params.level ?? 0.34, 0, 1, "level");
  voiceMix.gain.value = 1 / Math.sqrt(detunes.length);

  const oscillators = detunes.map((cents) => {
    const oscillator = context.createOscillator();
    oscillator.type = "sawtooth";
    oscillator.frequency.value = rootFrequency;
    oscillator.detune.value = cents;
    oscillator.connect(voiceMix);
    return oscillator;
  });

  subOscillator.type = "sine";
  subOscillator.frequency.value = rootFrequency / 2;
  subGain.gain.value = PAD_SUB_LEVEL;
  subOscillator.connect(subGain);
  subGain.connect(voiceMix);

  filter.type = "lowpass";
  filter.frequency.value = clampParam(params.cutoff ?? PAD_CUTOFF_HZ, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "cutoff");
  filter.Q.value = PAD_RESONANCE;

  lfo.type = "sine";
  lfo.frequency.value = clampParam(params.motion ?? PAD_LFO_HZ, MIN_LFO_HZ, MAX_LFO_HZ, "motion");
  lfoDepth.gain.value = PAD_LFO_DEPTH_HZ;
  lfo.connect(lfoDepth);
  lfoDepth.connect(filter.frequency);

  voiceMix.connect(filter);

  // The shimmer delay and reverb, built inline from the same primitives the
  // standalone modules use (NOT by importing them — a module composing another
  // module would be the plugin-imports-plugin mistake in a different file).
  const delayLeft = context.createDelay(MAX_DELAY_SECONDS);
  const delayRight = context.createDelay(MAX_DELAY_SECONDS);
  const delayFeedback = context.createGain();
  const delayDamping = context.createBiquadFilter();
  const delayMerger = context.createChannelMerger(2);
  const delayWet = context.createGain();

  delayLeft.delayTime.value = PAD_DELAY_SECONDS;
  delayRight.delayTime.value = PAD_DELAY_SECONDS * PAD_DELAY_SKEW;
  delayFeedback.gain.value = PAD_DELAY_FEEDBACK;
  delayDamping.type = "lowpass";
  delayDamping.frequency.value = PAD_DELAY_DAMPING_HZ;
  delayWet.gain.value = PAD_DELAY_WET;

  filter.connect(delayLeft);
  delayLeft.connect(delayRight);
  delayRight.connect(delayDamping);
  delayDamping.connect(delayFeedback);
  delayFeedback.connect(delayLeft);
  delayLeft.connect(delayMerger, 0, 0);
  delayRight.connect(delayMerger, 0, 1);
  delayMerger.connect(delayWet);

  const convolver = context.createConvolver();
  const reverbWet = context.createGain();
  convolver.normalize = true;
  convolver.buffer = resources.impulseResponse(params.space ?? "deepSpace");
  reverbWet.gain.value = clampParam(params.reverb ?? PAD_REVERB_WET, 0, 1, "reverb");

  filter.connect(output); // dry
  delayWet.connect(output);
  delayWet.connect(convolver);
  filter.connect(convolver);
  convolver.connect(reverbWet);
  reverbWet.connect(output);

  let started = false;
  return {
    inputs: { level: output.gain, cutoff: filter.frequency },
    outputs: { out: output },
    params: {
      level: output.gain,
      cutoff: filter.frequency,
      motion: lfo.frequency,
      reverb: reverbWet.gain,
      frequency: (value, when, ramp) => {
        const target = clampParam(value, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "frequency");
        for (const oscillator of oscillators) {
          if (ramp > 0) oscillator.frequency.setTargetAtTime(target, when, ramp);
          else oscillator.frequency.setValueAtTime(target, when);
        }
        if (ramp > 0) subOscillator.frequency.setTargetAtTime(target / 2, when, ramp);
        else subOscillator.frequency.setValueAtTime(target / 2, when);
      },
    },
    start() {
      if (started) return;
      for (const oscillator of oscillators) oscillator.start();
      subOscillator.start();
      lfo.start();
      started = true;
    },
    dispose() {
      for (const oscillator of oscillators) {
        if (started) oscillator.stop();
        oscillator.disconnect();
      }
      if (started) {
        subOscillator.stop();
        lfo.stop();
      }
      for (const node of [
        voiceMix, filter, lfo, lfoDepth, subOscillator, subGain, delayLeft, delayRight,
        delayFeedback, delayDamping, delayMerger, delayWet, convolver, reverbWet, output,
      ]) {
        node.disconnect();
      }
    },
    meta: { kind: "pad", label: "Ambience Pad" },
  };
}

// ─── 24. POLY PAD (the polyphonic voice pool) ────────────────────────────────

/**
 * POLY PAD — N independent voices with one shared tone-shaping chain, played by
 * note events rather than by a frequency knob.
 *
 * ── WHY THIS IS A NEW MODULE AND NOT A FLAG ON THE PAD ──────────────────────
 * "Polyphonic demos are important" (user, 2026-08-03). The obvious move is to
 * teach `padModule` to be polyphonic, and it is the wrong one for a stated
 * reason: the pad is a DRONE. Its whole interface is one `frequency` knob and a
 * sound that is always on, and every patch in both libraries relies on that —
 * SPACEY_PAD_DRONE connects it to an output and nothing else, and it plays. A
 * poly pad has no sound at rest and no frequency knob at all; it has a pitch
 * INPUT and a gate. Those are different modules that happen to share a timbre,
 * and merging them would mean a `poly: true` knob that silently changes what
 * every other knob on the card means.
 *
 * THE SEAM THIS ESTABLISHES, and it is the part meant to outlive this module: a
 * poly module is one that exposes `noteOn(note, frequency, time)` and
 * `noteOff(note, time)` alongside the ordinary instance shape. The ENGINE
 * dispatches to those (see engine.noteOn/noteOff) and nothing else in the engine
 * changes — MONO MODULES ARE UNTOUCHED, they simply do not declare the methods
 * and the engine says so loudly if you send them a note. That is the same
 * discipline `trigger` already follows.
 *
 * ── VOICES ARE BUILT EAGERLY, WHICH IS A REAL TRADE ─────────────────────────
 * All N voices exist from construction: oscillators started, gains at zero. The
 * alternative is building a voice per note-on, which is what dingModule does and
 * is right there — a bell is a one-shot whose voice dies on its own. A pad voice
 * is HELD, so per-note construction would allocate several AudioNodes inside the
 * note-on handler, i.e. on the gesture path, and connect them while sound is
 * playing. Eager voices cost CPU that is not being heard, which is why the count
 * is a knob with a ceiling (synth/voices.MAX_POLY_VOICES) rather than unbounded.
 *
 * ── THE ALLOCATION DECISION IS NOT HERE ─────────────────────────────────────
 * Which slot a note lands on, and which note gets stolen, is synth/voices.js —
 * pure, and tested in bare node. This module owns only the AudioNodes: given a
 * slot index, retune it and open its envelope. Keeping the two apart is what
 * makes "the 9th note steals the oldest" an ordinary assertion instead of
 * something you have to hear.
 */
function polyPadModule(context, params) {
  const output = context.createGain();
  const filter = context.createBiquadFilter();
  const lfo = context.createOscillator();
  const lfoDepth = context.createGain();

  const voiceCount = Math.floor(clampParam(params.voices ?? DEFAULT_POLY_VOICES, MIN_POLY_VOICES, MAX_POLY_VOICES, "voices"));
  const detunes = supersawDetunes(POLY_DETUNE_COUNT, params.spread ?? POLY_SPREAD_CENTS);

  output.gain.value = clampParam(params.level ?? 0.3, 0, 1, "level");

  filter.type = "lowpass";
  filter.frequency.value = clampParam(params.cutoff ?? POLY_CUTOFF_HZ, MIN_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "cutoff");
  filter.Q.value = POLY_RESONANCE;
  filter.connect(output);

  // The shared slow filter sweep — one LFO for the whole instrument, not one per
  // voice: a pad's motion is a property of the patch, and N independent sweeps
  // beating against each other is a chorus, not a pad.
  lfo.type = "sine";
  lfo.frequency.value = clampParam(params.motion ?? POLY_LFO_HZ, 0.01, 20, "motion");
  lfoDepth.gain.value = POLY_LFO_DEPTH_HZ;
  lfo.connect(lfoDepth);
  lfoDepth.connect(filter.frequency);

  /**
   * One voice: a small detuned saw stack through its own envelope gain.
   *
   * The envelope is an ordinary AudioParam ramp rather than the ADSR worklet,
   * deliberately: this module must work before `init()` has loaded the worklets
   * (a poly pad in a deck that loads mid-presentation), and attack/release on a
   * gain is exactly what a pad envelope is. The worklet ADSR remains the module
   * you patch when you want a shaped envelope on something else.
   */
  const voices = Array.from({ length: voiceCount }, () => {
    const gain = context.createGain();
    gain.gain.value = 0;
    const oscillators = detunes.map((cents) => {
      const oscillator = context.createOscillator();
      oscillator.type = "sawtooth";
      oscillator.frequency.value = POLY_REST_HZ;
      oscillator.detune.value = cents;
      oscillator.connect(gain);
      return oscillator;
    });
    gain.connect(filter);
    return { gain, oscillators };
  });

  // ── THE PITCH SEAM, AND WHY IT IS A ConstantSourceNode ──────────────────────
  // Identical in shape and in reasoning to dingModule's: `pitch` is the OFFSET of
  // a ConstantSourceNode, which makes it an ordinary AudioParam that any control
  // signal can be wired INTO and that Web Audio SUMS. So a keyboard's pitch
  // output and a transpose knob add up with no scaling module in between.
  //
  // It is SAMPLED AT NOTE-ON, not audio-rate, and that is the same ruling the
  // ding made for the same reason: a held chord whose voices all glide when the
  // pitch input moves is a siren, not a chord. The note being started belongs to
  // the pitch that is current when the key goes down.
  //
  // A caller MAY still name a frequency per note (engine.noteOn's third
  // argument, which is what a keyboard does — it knows exactly which key was
  // pressed). That WINS over the port, exactly as options.frequency wins for a
  // ding: naming a pitch for one specific note is more specific than a standing
  // wire. The port is for the patch that drives pitch by a wire alone.
  const pitchBus = createConstant(context, clampParam(params.pitch ?? POLY_REST_HZ, -MAX_AUDIBLE_HZ, MAX_AUDIBLE_HZ, "pitch"));
  pitchBus.start();

  const attack = () => clampParam(params.attack ?? POLY_ATTACK_SECONDS, 0.001, 4, "attack");
  const release = () => clampParam(params.release ?? POLY_RELEASE_SECONDS, 0.01, 8, "release");
  // Each voice carries 1/sqrt(N) of full scale so a held chord does not clip
  // where a single note did not — the same power-summing convention the supersaw
  // uses for its own stack.
  const voiceLevel = 1 / Math.sqrt(voiceCount);

  let started = false;
  return {
    inputs: { level: output.gain, cutoff: filter.frequency, pitch: pitchBus.offset },
    outputs: { out: output },
    params: {
      level: output.gain,
      cutoff: filter.frequency,
      motion: lfo.frequency,
      pitch: pitchBus.offset,
    },
    /**
     * Command. Sound `frequency` on voice `slot` at an audio-clock time.
     *
     * The pitch is set with `setValueAtTime` rather than ramped: a stolen voice
     * gliding from the note it was playing to the new one is a portamento
     * nobody asked for, and it is exactly what makes voice stealing audible.
     * The AMPLITUDE does ramp (the attack), which is what covers the switch.
     *
     * Args:
     *     slot (number): which voice, from synth/voices.js
     *     frequency (number): the note in Hz
     *     time (number): audio-clock time
     */
    noteOn(slot, frequency, time = context.currentTime) {
      const voice = voices[slot];
      if (!voice) throw new RangeError(`poly pad has ${voices.length} voices; no slot ${slot}`);
      // The caller's frequency wins; with none, the pitch PORT names the note.
      // Clamped rather than refused on this path: the value can be the sum of a
      // wire and an offset, and a modulation that briefly overshoots must not
      // throw on the audio path and kill the note.
      const named = frequency ?? pitchBus.offset.value;
      const hz = Math.max(MIN_AUDIBLE_HZ, Math.min(MAX_AUDIBLE_HZ, named));
      for (const oscillator of voice.oscillators) oscillator.frequency.setValueAtTime(hz, time);
      voice.gain.gain.cancelScheduledValues(time);
      // Anchor at the CURRENT value before ramping. Without this, a voice
      // stolen mid-release would jump to wherever its last scheduled ramp had
      // reached rather than continuing from where it audibly is — a click.
      voice.gain.gain.setValueAtTime(voice.gain.gain.value, time);
      voice.gain.gain.linearRampToValueAtTime(voiceLevel, time + attack());
    },
    /** Command. Release voice `slot`. Ramps to zero over the release time. */
    noteOff(slot, time = context.currentTime) {
      const voice = voices[slot];
      if (!voice) throw new RangeError(`poly pad has ${voices.length} voices; no slot ${slot}`);
      voice.gain.gain.cancelScheduledValues(time);
      voice.gain.gain.setValueAtTime(voice.gain.gain.value, time);
      voice.gain.gain.linearRampToValueAtTime(0, time + release());
    },
    start() {
      if (started) return;
      for (const voice of voices) for (const oscillator of voice.oscillators) oscillator.start();
      lfo.start();
      started = true;
    },
    dispose() {
      for (const voice of voices) {
        for (const oscillator of voice.oscillators) {
          if (started) oscillator.stop();
          oscillator.disconnect();
        }
        voice.gain.disconnect();
      }
      if (started) lfo.stop();
      // The pitch bus is a started source like any other; the engine's leak
      // check counts it, so it must be stopped as well as disconnected.
      pitchBus.stop();
      pitchBus.disconnect();
      for (const node of [filter, lfo, lfoDepth, output]) node.disconnect();
    },
    meta: { kind: "polyPad", label: "Poly Pad", voices: voiceCount },
  };
}

/** How many detuned saws make up ONE poly voice. Three, not the supersaw's
 *  seven: a poly pad may have eight voices sounding at once, and 56 oscillators
 *  is a real cost for a thickness nobody can hear inside a chord. */
const POLY_DETUNE_COUNT = 3;
const POLY_SPREAD_CENTS = 11;
const POLY_CUTOFF_HZ = 1400;
const POLY_RESONANCE = 1.2;
/** Slower than the mono pad's sweep — a chord already moves. */
const POLY_LFO_HZ = 0.09;
const POLY_LFO_DEPTH_HZ = 500;
/** Where a silent voice's oscillators park. Any audible frequency will do (they
 *  are at zero gain); a real one avoids a denormal-adjacent value. */
const POLY_REST_HZ = 220;
/** A pad's envelope: slow enough to swell, fast enough that a played chord
 *  arrives with the gesture rather than after it. */
const POLY_ATTACK_SECONDS = 0.12;
const POLY_RELEASE_SECONDS = 0.45;

/** Pad voicing constants — the "spacey by default" settings. */
const PAD_VOICES = 7;
const PAD_SPREAD_CENTS = 16;
const PAD_SUB_LEVEL = 0.3;
const PAD_CUTOFF_HZ = 900;
const PAD_RESONANCE = 3.5;

/** 0.06 Hz = one full sweep every ~16 s. Slow enough to read as "the sound is
 * alive" rather than as an audible effect. */
const PAD_LFO_HZ = 0.06;
const PAD_LFO_DEPTH_HZ = 700;

const PAD_DELAY_SECONDS = 0.52;

/** Left and right delay times deliberately unequal, so repeats never line up
 * into a single centred echo. */
const PAD_DELAY_SKEW = 1.37;
const PAD_DELAY_FEEDBACK = 0.42;
const PAD_DELAY_DAMPING_HZ = 1800;
const PAD_DELAY_WET = 0.4;
const PAD_REVERB_WET = 0.55;

// ─── The registry ────────────────────────────────────────────────────────────

/**
 * THE MODULE REGISTRY — type name -> factory. The engine's addModule() is a
 * lookup in this table and nothing more.
 *
 * 23 entries (see the count note at the top of this file). `whoosh` is not a
 * module:
 * a whoosh is a PATCH (noise -> filter sweep), which dev.html demonstrates —
 * making it a module would hide the modular paradigm the whole project is about.
 */
export const MODULE_FACTORIES = {
  output: outputModule,
  oscillator: oscillatorModule,
  supersaw: supersawModule,
  noise: noiseModule,
  filter: filterModule,
  adsr: adsrModule,
  vca: vcaModule,
  mixer: mixerModule,
  lfo: lfoModule,
  delay: delayModule,
  reverb: reverbModule,
  bitcrush: bitcrushModule,
  quantize: quantizeModule,
  sampleHold: sampleHoldModule,
  trigger: triggerModule,
  eq3: eq3Module,
  clock: clockModule,
  sequencer: sequencerModule,
  sampler: samplerModule,
  meter: meterModule,
  spectrum: spectrumModule,
  ding: dingModule,
  pad: padModule,
  polyPad: polyPadModule,
};

/** Query. The module type names, for UI enumeration. */
export function moduleTypes() {
  return Object.keys(MODULE_FACTORIES);
}
